/*
 * This file is generated by jOOQ.
 */
package stroom.activity.impl.db;


import javax.annotation.Generated;

import stroom.activity.impl.db.tables.Activity;


/**
 * Convenience access to all tables in stroom
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>stroom.activity</code>.
     */
    public static final Activity ACTIVITY = stroom.activity.impl.db.tables.Activity.ACTIVITY;
}
