/*
 * This file is generated by jOOQ.
 */
package stroom.dashboard.impl.db.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import stroom.dashboard.impl.db.jooq.tables.VisualisationAssets;
import stroom.dashboard.impl.db.jooq.tables.VisualisationAssetsDraft;
import stroom.dashboard.impl.db.jooq.tables.VisualisationAssetsUpdateDelete;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Stroom extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>stroom</code>
     */
    public static final Stroom STROOM = new Stroom();

    /**
     * The table <code>stroom.visualisation_assets</code>.
     */
    public final VisualisationAssets VISUALISATION_ASSETS = VisualisationAssets.VISUALISATION_ASSETS;

    /**
     * The table <code>stroom.visualisation_assets_draft</code>.
     */
    public final VisualisationAssetsDraft VISUALISATION_ASSETS_DRAFT = VisualisationAssetsDraft.VISUALISATION_ASSETS_DRAFT;

    /**
     * The table <code>stroom.visualisation_assets_update_delete</code>.
     */
    public final VisualisationAssetsUpdateDelete VISUALISATION_ASSETS_UPDATE_DELETE = VisualisationAssetsUpdateDelete.VISUALISATION_ASSETS_UPDATE_DELETE;

    /**
     * No further instances allowed
     */
    private Stroom() {
        super("stroom", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            VisualisationAssets.VISUALISATION_ASSETS,
            VisualisationAssetsDraft.VISUALISATION_ASSETS_DRAFT,
            VisualisationAssetsUpdateDelete.VISUALISATION_ASSETS_UPDATE_DELETE
        );
    }
}
