/*
 * This file is generated by jOOQ.
 */
package stroom.security.impl.db.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import stroom.security.impl.db.jooq.tables.ApiKey;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ApiKeyRecord extends UpdatableRecordImpl<ApiKeyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>stroom.api_key.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>stroom.api_key.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>stroom.api_key.version</code>.
     */
    public void setVersion(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>stroom.api_key.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>stroom.api_key.create_time_ms</code>.
     */
    public void setCreateTimeMs(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>stroom.api_key.create_time_ms</code>.
     */
    public Long getCreateTimeMs() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>stroom.api_key.create_user</code>.
     */
    public void setCreateUser(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>stroom.api_key.create_user</code>.
     */
    public String getCreateUser() {
        return (String) get(3);
    }

    /**
     * Setter for <code>stroom.api_key.update_time_ms</code>.
     */
    public void setUpdateTimeMs(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>stroom.api_key.update_time_ms</code>.
     */
    public Long getUpdateTimeMs() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>stroom.api_key.update_user</code>.
     */
    public void setUpdateUser(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>stroom.api_key.update_user</code>.
     */
    public String getUpdateUser() {
        return (String) get(5);
    }

    /**
     * Setter for <code>stroom.api_key.fk_owner_uuid</code>.
     */
    public void setFkOwnerUuid(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>stroom.api_key.fk_owner_uuid</code>.
     */
    public String getFkOwnerUuid() {
        return (String) get(6);
    }

    /**
     * Setter for <code>stroom.api_key.api_key_hash</code>.
     */
    public void setApiKeyHash(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>stroom.api_key.api_key_hash</code>.
     */
    public String getApiKeyHash() {
        return (String) get(7);
    }

    /**
     * Setter for <code>stroom.api_key.api_key_prefix</code>.
     */
    public void setApiKeyPrefix(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>stroom.api_key.api_key_prefix</code>.
     */
    public String getApiKeyPrefix() {
        return (String) get(8);
    }

    /**
     * Setter for <code>stroom.api_key.expires_on_ms</code>.
     */
    public void setExpiresOnMs(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>stroom.api_key.expires_on_ms</code>.
     */
    public Long getExpiresOnMs() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>stroom.api_key.name</code>.
     */
    public void setName(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>stroom.api_key.name</code>.
     */
    public String getName() {
        return (String) get(10);
    }

    /**
     * Setter for <code>stroom.api_key.comments</code>.
     */
    public void setComments(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>stroom.api_key.comments</code>.
     */
    public String getComments() {
        return (String) get(11);
    }

    /**
     * Setter for <code>stroom.api_key.enabled</code>.
     */
    public void setEnabled(Boolean value) {
        set(12, value);
    }

    /**
     * Getter for <code>stroom.api_key.enabled</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(12);
    }

    /**
     * Setter for <code>stroom.api_key.hash_algorithm</code>.
     */
    public void setHashAlgorithm(Byte value) {
        set(13, value);
    }

    /**
     * Getter for <code>stroom.api_key.hash_algorithm</code>.
     */
    public Byte getHashAlgorithm() {
        return (Byte) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ApiKeyRecord
     */
    public ApiKeyRecord() {
        super(ApiKey.API_KEY);
    }

    /**
     * Create a detached, initialised ApiKeyRecord
     */
    public ApiKeyRecord(Integer id, Integer version, Long createTimeMs, String createUser, Long updateTimeMs, String updateUser, String fkOwnerUuid, String apiKeyHash, String apiKeyPrefix, Long expiresOnMs, String name, String comments, Boolean enabled, Byte hashAlgorithm) {
        super(ApiKey.API_KEY);

        setId(id);
        setVersion(version);
        setCreateTimeMs(createTimeMs);
        setCreateUser(createUser);
        setUpdateTimeMs(updateTimeMs);
        setUpdateUser(updateUser);
        setFkOwnerUuid(fkOwnerUuid);
        setApiKeyHash(apiKeyHash);
        setApiKeyPrefix(apiKeyPrefix);
        setExpiresOnMs(expiresOnMs);
        setName(name);
        setComments(comments);
        setEnabled(enabled);
        setHashAlgorithm(hashAlgorithm);
        resetChangedOnNotNull();
    }
}
