/*
 * This file is generated by jOOQ.
 */
package stroom.security.impl.db.jooq.tables.records;


import stroom.security.impl.db.jooq.tables.PermissionDoc;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PermissionDocRecord extends UpdatableRecordImpl<PermissionDocRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>stroom.permission_doc.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>stroom.permission_doc.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>stroom.permission_doc.user_uuid</code>.
     */
    public void setUserUuid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>stroom.permission_doc.user_uuid</code>.
     */
    public String getUserUuid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>stroom.permission_doc.doc_uuid</code>.
     */
    public void setDocUuid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>stroom.permission_doc.doc_uuid</code>.
     */
    public String getDocUuid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>stroom.permission_doc.permission_id</code>.
     */
    public void setPermissionId(UByte value) {
        set(3, value);
    }

    /**
     * Getter for <code>stroom.permission_doc.permission_id</code>.
     */
    public UByte getPermissionId() {
        return (UByte) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PermissionDocRecord
     */
    public PermissionDocRecord() {
        super(PermissionDoc.PERMISSION_DOC);
    }

    /**
     * Create a detached, initialised PermissionDocRecord
     */
    public PermissionDocRecord(Long id, String userUuid, String docUuid, UByte permissionId) {
        super(PermissionDoc.PERMISSION_DOC);

        setId(id);
        setUserUuid(userUuid);
        setDocUuid(docUuid);
        setPermissionId(permissionId);
        resetChangedOnNotNull();
    }
}
