/*
 * Copyright 2018 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { library } from "@fortawesome/fontawesome-svg-core";

import {
  faAngleDown,
  faAngleRight,
  faAngleUp,
  faArrowLeft,
  faArrowsAlt,
  faBan,
  faBars,
  faBomb,
  faCaretDown,
  faCaretRight,
  faCheck,
  faChevronLeft,
  faChevronRight,
  faCircle,
  faCog,
  faCogs,
  faCopy,
  faDatabase,
  faEdit,
  faExclamationCircle,
  faExclamationTriangle,
  faEye,
  faEyeSlash,
  faFile,
  faFolder,
  faFolderOpen,
  faFolderPlus,
  faGripVertical,
  faHistory,
  faHome,
  faICursor,
  faInfo,
  faInfoCircle,
  faKey,
  faPlay,
  faPlus,
  faQuestion,
  faQuestionCircle,
  faRecycle,
  faSave,
  faSearch,
  faSortAlphaDown,
  faSortAlphaDownAlt,
  faTasks,
  faTimes,
  faTrash,
  faTrashAlt,
  faUser,
  faUsers,
} from "@fortawesome/free-solid-svg-icons";

export default () =>
  library.add(
    faAngleDown,
    faAngleRight,
    faAngleUp,
    faArrowLeft,
    faArrowsAlt,
    faBan,
    faBars,
    faBomb,
    faCaretDown,
    faCaretRight,
    faCheck,
    faChevronLeft,
    faChevronRight,
    faCircle,
    faCog,
    faCogs,
    faCopy,
    faDatabase,
    faEdit,
    faExclamationCircle,
    faExclamationTriangle,
    faEye,
    faEyeSlash,
    faFile,
    faFolder,
    faFolderOpen,
    faFolderPlus,
    faGripVertical,
    faHistory,
    faHome,
    faICursor,
    faInfo,
    faInfoCircle,
    faKey,
    faPlay,
    faPlus,
    faQuestion,
    faQuestionCircle,
    faRecycle,
    faSave,
    faSearch,
    faSortAlphaDown,
    faSortAlphaDownAlt,
    faTasks,
    faTimes,
    faTrash,
    faTrashAlt,
    faUser,
    faUsers,
  );
