/*
 * This file is generated by jOOQ.
 */
package stroom.security.impl.db.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import stroom.security.impl.db.jooq.Keys;
import stroom.security.impl.db.jooq.Stroom;
import stroom.security.impl.db.jooq.tables.StroomUser.StroomUserPath;
import stroom.security.impl.db.jooq.tables.records.StroomUserGroupRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StroomUserGroup extends TableImpl<StroomUserGroupRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>stroom.stroom_user_group</code>
     */
    public static final StroomUserGroup STROOM_USER_GROUP = new StroomUserGroup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StroomUserGroupRecord> getRecordType() {
        return StroomUserGroupRecord.class;
    }

    /**
     * The column <code>stroom.stroom_user_group.id</code>.
     */
    public final TableField<StroomUserGroupRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>stroom.stroom_user_group.user_uuid</code>.
     */
    public final TableField<StroomUserGroupRecord, String> USER_UUID = createField(DSL.name("user_uuid"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stroom.stroom_user_group.group_uuid</code>.
     */
    public final TableField<StroomUserGroupRecord, String> GROUP_UUID = createField(DSL.name("group_uuid"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private StroomUserGroup(Name alias, Table<StroomUserGroupRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private StroomUserGroup(Name alias, Table<StroomUserGroupRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>stroom.stroom_user_group</code> table reference
     */
    public StroomUserGroup(String alias) {
        this(DSL.name(alias), STROOM_USER_GROUP);
    }

    /**
     * Create an aliased <code>stroom.stroom_user_group</code> table reference
     */
    public StroomUserGroup(Name alias) {
        this(alias, STROOM_USER_GROUP);
    }

    /**
     * Create a <code>stroom.stroom_user_group</code> table reference
     */
    public StroomUserGroup() {
        this(DSL.name("stroom_user_group"), null);
    }

    public <O extends Record> StroomUserGroup(Table<O> path, ForeignKey<O, StroomUserGroupRecord> childPath, InverseForeignKey<O, StroomUserGroupRecord> parentPath) {
        super(path, childPath, parentPath, STROOM_USER_GROUP);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class StroomUserGroupPath extends StroomUserGroup implements Path<StroomUserGroupRecord> {
        public <O extends Record> StroomUserGroupPath(Table<O> path, ForeignKey<O, StroomUserGroupRecord> childPath, InverseForeignKey<O, StroomUserGroupRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private StroomUserGroupPath(Name alias, Table<StroomUserGroupRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public StroomUserGroupPath as(String alias) {
            return new StroomUserGroupPath(DSL.name(alias), this);
        }

        @Override
        public StroomUserGroupPath as(Name alias) {
            return new StroomUserGroupPath(alias, this);
        }

        @Override
        public StroomUserGroupPath as(Table<?> alias) {
            return new StroomUserGroupPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Stroom.STROOM;
    }

    @Override
    public Identity<StroomUserGroupRecord, Long> getIdentity() {
        return (Identity<StroomUserGroupRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<StroomUserGroupRecord> getPrimaryKey() {
        return Keys.KEY_STROOM_USER_GROUP_PRIMARY;
    }

    @Override
    public List<UniqueKey<StroomUserGroupRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_STROOM_USER_GROUP_STROOM_USER_GROUP_GROUP_UUID_USER_UUID_IDX, Keys.KEY_STROOM_USER_GROUP_STROOM_USER_GROUP_USER_UUID_GROUP_UUID_IDX);
    }

    @Override
    public List<ForeignKey<StroomUserGroupRecord, ?>> getReferences() {
        return Arrays.asList(Keys.STROOM_USER_GROUP_FK_USER_UUID, Keys.STROOM_USER_GROUP_FK_GROUP_UUID);
    }

    private transient StroomUserPath _stroomUserGroupFkUserUuid;

    /**
     * Get the implicit join path to the <code>stroom.stroom_user</code> table,
     * via the <code>stroom_user_group_fk_user_uuid</code> key.
     */
    public StroomUserPath stroomUserGroupFkUserUuid() {
        if (_stroomUserGroupFkUserUuid == null)
            _stroomUserGroupFkUserUuid = new StroomUserPath(this, Keys.STROOM_USER_GROUP_FK_USER_UUID, null);

        return _stroomUserGroupFkUserUuid;
    }

    private transient StroomUserPath _stroomUserGroupFkGroupUuid;

    /**
     * Get the implicit join path to the <code>stroom.stroom_user</code> table,
     * via the <code>stroom_user_group_fk_group_uuid</code> key.
     */
    public StroomUserPath stroomUserGroupFkGroupUuid() {
        if (_stroomUserGroupFkGroupUuid == null)
            _stroomUserGroupFkGroupUuid = new StroomUserPath(this, Keys.STROOM_USER_GROUP_FK_GROUP_UUID, null);

        return _stroomUserGroupFkGroupUuid;
    }

    @Override
    public StroomUserGroup as(String alias) {
        return new StroomUserGroup(DSL.name(alias), this);
    }

    @Override
    public StroomUserGroup as(Name alias) {
        return new StroomUserGroup(alias, this);
    }

    @Override
    public StroomUserGroup as(Table<?> alias) {
        return new StroomUserGroup(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public StroomUserGroup rename(String name) {
        return new StroomUserGroup(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public StroomUserGroup rename(Name name) {
        return new StroomUserGroup(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public StroomUserGroup rename(Table<?> name) {
        return new StroomUserGroup(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StroomUserGroup where(Condition condition) {
        return new StroomUserGroup(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StroomUserGroup where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StroomUserGroup where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StroomUserGroup where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StroomUserGroup where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StroomUserGroup where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StroomUserGroup where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StroomUserGroup where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StroomUserGroup whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StroomUserGroup whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
