@startuml

title Forward Stored Data

participant ProxyRepoSources
participant SourceForwarder
database db
database repo
participant ForwardStreamHandlers
participant Cleanup
actor Destination

ProxyRepoSources --// SourceForwarder: onChange
SourceForwarder -> db: Find new sources
SourceForwarder -// SourceForwarder++: Forward Sources
SourceForwarder -// SourceForwarder++: Forward Source
SourceForwarder -> repo: read
SourceForwarder -> ForwardStreamHandlers: write
ForwardStreamHandlers --> Destination: handle
SourceForwarder -> db: record 'forward_source'

SourceForwarder -> db: record 'source' forwarded
return
return

SourceForwarder --// Cleanup: onChange

@enduml