@startuml

title Forward Stored Data

participant ProxyRepoSources
participant SourceForwarder
database db
database repo
participant ForwardStreamHandlers
actor Destination
participant Cleanup

ProxyRepoSources --// SourceForwarder: onChange
SourceForwarder -> db: Find new sources
SourceForwarder -// SourceForwarder++: Forward Sources
SourceForwarder -// SourceForwarder++: Forward Source
SourceForwarder -> repo: read
SourceForwarder -> ForwardStreamHandlers: write
ForwardStreamHandlers --> Destination: handle
SourceForwarder -> db: record FORWARD_SOURCE

SourceForwarder -> db: record SOURCE forwarded
return
return

SourceForwarder --// Cleanup: onChange

@enduml