@startuml

title Receive And Store Data

actor Supplier
participant ProxyRequestHandler
participant ProxyRepositoryStreamHandler
participant ProxyRepo
participant ProxyRepoSources
database repo
database db
actor ChangeListener

Supplier --> ProxyRequestHandler: HTTP POST
ProxyRequestHandler -> ProxyRepositoryStreamHandler: handle
ProxyRepositoryStreamHandler -> ProxyRepo: getStroomZipOutputStream
ProxyRepositoryStreamHandler ->> repo: Write data
ProxyRepo -> repo: Add meta file
ProxyRepo -> repo: Unlock zip file
ProxyRepo ->> ProxyRepoSources: addSource
ProxyRepoSources ->> db: Add SOURCE record
ProxyRepoSources --// ChangeListener: onChange
ProxyRequestHandler --> Supplier: 200 Response


@enduml