/*
 * This file is generated by jOOQ.
 */
package stroom.analytics.impl.db.jooq;


import stroom.analytics.impl.db.jooq.tables.AnalyticProcess;
import stroom.analytics.impl.db.jooq.tables.AnalyticProcessTracker;


/**
 * Convenience access to all tables in stroom.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>stroom.analytic_process</code>.
     */
    public static final AnalyticProcess ANALYTIC_PROCESS = AnalyticProcess.ANALYTIC_PROCESS;

    /**
     * The table <code>stroom.analytic_process_tracker</code>.
     */
    public static final AnalyticProcessTracker ANALYTIC_PROCESS_TRACKER = AnalyticProcessTracker.ANALYTIC_PROCESS_TRACKER;
}
