/*
 * This file is generated by jOOQ.
 */
package stroom.node.impl.db.jooq;


import stroom.node.impl.db.jooq.tables.Node;


/**
 * Convenience access to all tables in stroom.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>stroom.node</code>.
     */
    public static final Node NODE = Node.NODE;
}
