cd stroom-meta/stroom-meta-impl-db-jooq
../../gradlew generateJooq
cd -
cd stroom-dashboard/stroom-storedquery-impl-db-jooq
../../gradlew generateJooq
cd -
cd stroom-data/stroom-data-store-impl-fs-db-jooq
../../gradlew generateJooq
cd -
cd stroom-node/stroom-node-impl-db-jooq
../../gradlew generateJooq
cd -
cd stroom-security/stroom-security-identity-db-jooq
../../gradlew generateJooq
cd -
cd stroom-security/stroom-security-impl-db-jooq
../../gradlew generateJooq
cd -
cd stroom-annotation/stroom-annotation-impl-db-jooq
../../gradlew generateJooq
cd -
cd stroom-processor/stroom-processor-impl-db-jooq
../../gradlew generateJooq
cd -
cd stroom-cluster/stroom-cluster-lock-impl-db-jooq
../../gradlew generateJooq
cd -
cd stroom-activity/stroom-activity-impl-db-jooq
../../gradlew generateJooq
cd -
cd stroom-processor/stroom-processor-impl-db-jooq
../../gradlew generateJooq
cd -
cd stroom-annotation/stroom-annotation-impl-db-jooq
../../gradlew generateJooq
cd -
cd stroom-cluster/stroom-cluster-lock-impl-db-jooq
../../gradlew generateJooq
cd -
cd stroom-config/stroom-config-global-impl-db-jooq
../../gradlew generateJooq
cd -
cd stroom-explorer/stroom-explorer-impl-db-jooq
../../gradlew generateJooq
cd -
cd stroom-gitrepo/stroom-gitrepo-impl-db-jooq
../../gradlew generateJooq
cd -
cd stroom-index/stroom-index-impl-db-jooq
../../gradlew generateJooq
cd -
cd stroom-job/stroom-job-impl-db-jooq
../../gradlew generateJooq
cd -
cd stroom-analytics/stroom-analytics-impl-db-jooq
../../gradlew generateJooq
cd -
cd stroom-query/stroom-query-datasource-impl-db-jooq
../../gradlew generateJooq
cd -
cd stroom-credentials/stroom-credentials-impl-db-jooq
../../gradlew generateJooq
cd -
