/*
 * This file is generated by jOOQ.
 */
package stroom.processor.impl.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import stroom.processor.impl.db.tables.Processor;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProcessorRecord extends UpdatableRecordImpl<ProcessorRecord> implements Record9<Integer, Byte, String, String, String, String, Boolean, Long, Long> {

    private static final long serialVersionUID = -2141560161;

    /**
     * Setter for <code>stroom.processor.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>stroom.processor.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>stroom.processor.version</code>.
     */
    public void setVersion(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>stroom.processor.version</code>.
     */
    public Byte getVersion() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>stroom.processor.create_user</code>.
     */
    public void setCreateUser(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>stroom.processor.create_user</code>.
     */
    public String getCreateUser() {
        return (String) get(2);
    }

    /**
     * Setter for <code>stroom.processor.update_user</code>.
     */
    public void setUpdateUser(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>stroom.processor.update_user</code>.
     */
    public String getUpdateUser() {
        return (String) get(3);
    }

    /**
     * Setter for <code>stroom.processor.task_type</code>.
     */
    public void setTaskType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>stroom.processor.task_type</code>.
     */
    public String getTaskType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>stroom.processor.pipeline_uuid</code>.
     */
    public void setPipelineUuid(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>stroom.processor.pipeline_uuid</code>.
     */
    public String getPipelineUuid() {
        return (String) get(5);
    }

    /**
     * Setter for <code>stroom.processor.enabled</code>.
     */
    public void setEnabled(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>stroom.processor.enabled</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>stroom.processor.create_time_ms</code>.
     */
    public void setCreateTimeMs(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>stroom.processor.create_time_ms</code>.
     */
    public Long getCreateTimeMs() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>stroom.processor.update_time_ms</code>.
     */
    public void setUpdateTimeMs(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>stroom.processor.update_time_ms</code>.
     */
    public Long getUpdateTimeMs() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Byte, String, String, String, String, Boolean, Long, Long> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Byte, String, String, String, String, Boolean, Long, Long> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Processor.PROCESSOR.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field2() {
        return Processor.PROCESSOR.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Processor.PROCESSOR.CREATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Processor.PROCESSOR.UPDATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Processor.PROCESSOR.TASK_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Processor.PROCESSOR.PIPELINE_UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return Processor.PROCESSOR.ENABLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return Processor.PROCESSOR.CREATE_TIME_MS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return Processor.PROCESSOR.UPDATE_TIME_MS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component2() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getTaskType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getPipelineUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component7() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component8() {
        return getCreateTimeMs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component9() {
        return getUpdateTimeMs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value2() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getTaskType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPipelineUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getCreateTimeMs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getUpdateTimeMs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProcessorRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProcessorRecord value2(Byte value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProcessorRecord value3(String value) {
        setCreateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProcessorRecord value4(String value) {
        setUpdateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProcessorRecord value5(String value) {
        setTaskType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProcessorRecord value6(String value) {
        setPipelineUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProcessorRecord value7(Boolean value) {
        setEnabled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProcessorRecord value8(Long value) {
        setCreateTimeMs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProcessorRecord value9(Long value) {
        setUpdateTimeMs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProcessorRecord values(Integer value1, Byte value2, String value3, String value4, String value5, String value6, Boolean value7, Long value8, Long value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProcessorRecord
     */
    public ProcessorRecord() {
        super(Processor.PROCESSOR);
    }

    /**
     * Create a detached, initialised ProcessorRecord
     */
    public ProcessorRecord(Integer id, Byte version, String createUser, String updateUser, String taskType, String pipelineUuid, Boolean enabled, Long createTimeMs, Long updateTimeMs) {
        super(Processor.PROCESSOR);

        set(0, id);
        set(1, version);
        set(2, createUser);
        set(3, updateUser);
        set(4, taskType);
        set(5, pipelineUuid);
        set(6, enabled);
        set(7, createTimeMs);
        set(8, updateTimeMs);
    }
}
