package stroom.test;

import org.junit.jupiter.api.Disabled;

//@SelectClasses({
//        TestDashboardStoreImpl.class,
//        stroom.docstore.impl.db.TestDBPersistence.class,
//        stroom.explorer.TestExplorerTree.class,
//        stroom.importexport.TestImportExportDashboards.class,
//        stroom.importexport.TestImportExportSerializer.class,
//        stroom.importexport.TestImportExportServiceImpl.class,
//        stroom.importexport.TestImportExportServiceImpl2.class,
//        stroom.importexport.TestImportExportServiceImpl3.class,
//        stroom.index.TestIndexStoreImpl.class,
//        stroom.index.TestIndexShardServiceImpl.class,
//        stroom.index.TestIndexShardWriterImpl.class,
//        stroom.jobsystem.TestClusterLockService.class,
//        stroom.jobsystem.TestJobNodeService.class,
//        stroom.node.TestDefaultNodeFactory.class,
//        stroom.node.TestDefaultNodeService.class,
//        stroom.node.TestVolumeService.class,
//        stroom.pipeline.task.TestFullTranslationTask.class,
//        stroom.pipeline.task.TestFullTranslationTaskAndStepping.class,
//        stroom.pipeline.task.TestTranslationStepping.class,
//        stroom.policy.TestDataRetentionStreamFinder.class,
//        stroom.pipeline.refdata.TestReferenceDataWithCache.class,
//        stroom.script.TestScriptStoreImpl.class,
//        stroom.search.TestBasicSearch.class,
//        stroom.search.TestBasicSearch_EndToEnd.class,
//        stroom.search.TestDictionaryStoreImpl.class,
//        stroom.search.TestEventSearch.class,
//        stroom.search.TestInteractiveSearch.class,
//        stroom.search.TestQueryServiceImpl.class,
//        stroom.search.TestTagCloudSearch.class,
//        stroom.security.TestAppPermissionServiceImpl.class,
//        stroom.security.TestDocumentPermissionsServiceImpl.class,
//        stroom.security.TestUserServiceImpl.class,
//        stroom.statistics.impl.common.TestStatisticsDataSourceImportExportSerializer.class,
//        stroom.statistics.sql.TestSQLStatisticAggregationManager.class,
//        stroom.statistics.sql.TestSQLStatisticFlushTaskHandler.class,
//        stroom.stats.TestStroomStatsStoreImportExportSerializer.class,
//        TestFileSystemZipProcessor.class,
//        TestFileSystemStreamMaintenanceService.class,
//        TestFileSystemStreamStore.class,
//        stroom.data.store.upload.TestStreamUploadDownloadTaskHandler.class,
//        stroom.streamtask.TestDataRetentionExecutor.class,
//        stroom.streamtask.TestDataRetentionTransactionHelper.class,
//        TestFileSystemCleanTask.class,
//        stroom.streamtask.TestProxyAggregationTask.class,
//        TestStreamArchiveTask.class,
//        stroom.streamtask.TestProcessorFilterService.class,
//        stroom.streamtask.TestStreamRetentionExecutor.class,
//        stroom.streamtask.TestProcessorFilterTaskManager.class,
//        stroom.streamtask.TestProcessorFilterTaskManagerTransactionHelper.class,
//        stroom.streamtask.TestStreamTaskService.class,
//        stroom.streamtask.TestStreamTaskServiceBatchLocking.class,
//        stroom.streamtask.TestTranslationStreamTaskServiceImportExport.class,
//        stroom.task.TestTaskManagerImpl.class,
//        stroom.test.TestAbstractCoreIntegrationTest.class,
//        TestXMLSchemaStoreImpl.class
//})
@Disabled
public class AbstractCoreTestSuite {
}
