/*
 * This file is generated by jOOQ.
 */
package stroom.data.store.impl.fs.db.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import stroom.data.store.impl.fs.db.jooq.tables.FsOrphanedMetaTracker;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FsOrphanedMetaTrackerRecord extends UpdatableRecordImpl<FsOrphanedMetaTrackerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>stroom.fs_orphaned_meta_tracker.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>stroom.fs_orphaned_meta_tracker.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>stroom.fs_orphaned_meta_tracker.min_meta_id</code>.
     */
    public void setMinMetaId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>stroom.fs_orphaned_meta_tracker.min_meta_id</code>.
     */
    public Long getMinMetaId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FsOrphanedMetaTrackerRecord
     */
    public FsOrphanedMetaTrackerRecord() {
        super(FsOrphanedMetaTracker.FS_ORPHANED_META_TRACKER);
    }

    /**
     * Create a detached, initialised FsOrphanedMetaTrackerRecord
     */
    public FsOrphanedMetaTrackerRecord(Integer id, Long minMetaId) {
        super(FsOrphanedMetaTracker.FS_ORPHANED_META_TRACKER);

        setId(id);
        setMinMetaId(minMetaId);
        resetChangedOnNotNull();
    }
}
