/*
 * This file is generated by jOOQ.
 */
package stroom.proxy.repo.db.jooq;


import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import stroom.proxy.repo.db.jooq.tables.ZipData;
import stroom.proxy.repo.db.jooq.tables.ZipSource;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index SQLITE_AUTOINDEX_ZIP_DATA_1 = Indexes0.SQLITE_AUTOINDEX_ZIP_DATA_1;
    public static final Index SQLITE_AUTOINDEX_ZIP_SOURCE_1 = Indexes0.SQLITE_AUTOINDEX_ZIP_SOURCE_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index SQLITE_AUTOINDEX_ZIP_DATA_1 = Internal.createIndex("sqlite_autoindex_zip_data_1", ZipData.ZIP_DATA, new OrderField[] { ZipData.ZIP_DATA.NAME, ZipData.ZIP_DATA.FK_ZIP_SOURCE_ID }, true);
        public static Index SQLITE_AUTOINDEX_ZIP_SOURCE_1 = Internal.createIndex("sqlite_autoindex_zip_source_1", ZipSource.ZIP_SOURCE, new OrderField[] { ZipSource.ZIP_SOURCE.PATH }, true);
    }
}
