/*
 * This file is generated by jOOQ.
 */
package stroom.proxy.repo.db.jooq;


import javax.annotation.processing.Generated;

import stroom.proxy.repo.db.jooq.tables.ZipData;
import stroom.proxy.repo.db.jooq.tables.ZipDest;
import stroom.proxy.repo.db.jooq.tables.ZipDestData;
import stroom.proxy.repo.db.jooq.tables.ZipEntry;
import stroom.proxy.repo.db.jooq.tables.ZipSource;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>zip_data</code>.
     */
    public static final ZipData ZIP_DATA = ZipData.ZIP_DATA;

    /**
     * The table <code>zip_dest</code>.
     */
    public static final ZipDest ZIP_DEST = ZipDest.ZIP_DEST;

    /**
     * The table <code>zip_dest_data</code>.
     */
    public static final ZipDestData ZIP_DEST_DATA = ZipDestData.ZIP_DEST_DATA;

    /**
     * The table <code>zip_entry</code>.
     */
    public static final ZipEntry ZIP_ENTRY = ZipEntry.ZIP_ENTRY;

    /**
     * The table <code>zip_source</code>.
     */
    public static final ZipSource ZIP_SOURCE = ZipSource.ZIP_SOURCE;
}
