/*
 * This file is generated by jOOQ.
 */
package stroom.config.impl.db.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import stroom.config.impl.db.jooq.Keys;
import stroom.config.impl.db.jooq.Stroom;
import stroom.config.impl.db.jooq.tables.records.ConfigRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Config extends TableImpl<ConfigRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>stroom.config</code>
     */
    public static final Config CONFIG = new Config();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ConfigRecord> getRecordType() {
        return ConfigRecord.class;
    }

    /**
     * The column <code>stroom.config.id</code>.
     */
    public final TableField<ConfigRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>stroom.config.version</code>.
     */
    public final TableField<ConfigRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>stroom.config.create_time_ms</code>.
     */
    public final TableField<ConfigRecord, Long> CREATE_TIME_MS = createField(DSL.name("create_time_ms"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>stroom.config.create_user</code>.
     */
    public final TableField<ConfigRecord, String> CREATE_USER = createField(DSL.name("create_user"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stroom.config.update_time_ms</code>.
     */
    public final TableField<ConfigRecord, Long> UPDATE_TIME_MS = createField(DSL.name("update_time_ms"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>stroom.config.update_user</code>.
     */
    public final TableField<ConfigRecord, String> UPDATE_USER = createField(DSL.name("update_user"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stroom.config.name</code>.
     */
    public final TableField<ConfigRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stroom.config.val</code>.
     */
    public final TableField<ConfigRecord, String> VAL = createField(DSL.name("val"), SQLDataType.CLOB.nullable(false), this, "");

    private Config(Name alias, Table<ConfigRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Config(Name alias, Table<ConfigRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>stroom.config</code> table reference
     */
    public Config(String alias) {
        this(DSL.name(alias), CONFIG);
    }

    /**
     * Create an aliased <code>stroom.config</code> table reference
     */
    public Config(Name alias) {
        this(alias, CONFIG);
    }

    /**
     * Create a <code>stroom.config</code> table reference
     */
    public Config() {
        this(DSL.name("config"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Stroom.STROOM;
    }

    @Override
    public Identity<ConfigRecord, Integer> getIdentity() {
        return (Identity<ConfigRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ConfigRecord> getPrimaryKey() {
        return Keys.KEY_CONFIG_PRIMARY;
    }

    @Override
    public List<UniqueKey<ConfigRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_CONFIG_NAME);
    }

    @Override
    public TableField<ConfigRecord, Integer> getRecordVersion() {
        return VERSION;
    }

    @Override
    public Config as(String alias) {
        return new Config(DSL.name(alias), this);
    }

    @Override
    public Config as(Name alias) {
        return new Config(alias, this);
    }

    @Override
    public Config as(Table<?> alias) {
        return new Config(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Config rename(String name) {
        return new Config(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Config rename(Name name) {
        return new Config(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Config rename(Table<?> name) {
        return new Config(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Config where(Condition condition) {
        return new Config(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Config where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Config where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Config where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Config where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Config where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Config where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Config where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Config whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Config whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
