/*
 * This file is generated by jOOQ.
 */
package stroom.config.impl.db.jooq;


import stroom.config.impl.db.jooq.tables.Config;
import stroom.config.impl.db.jooq.tables.ConfigUpdateTracker;
import stroom.config.impl.db.jooq.tables.Preferences;


/**
 * Convenience access to all tables in stroom.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>stroom.config</code>.
     */
    public static final Config CONFIG = Config.CONFIG;

    /**
     * The table <code>stroom.config_update_tracker</code>.
     */
    public static final ConfigUpdateTracker CONFIG_UPDATE_TRACKER = ConfigUpdateTracker.CONFIG_UPDATE_TRACKER;

    /**
     * The table <code>stroom.preferences</code>.
     */
    public static final Preferences PREFERENCES = Preferences.PREFERENCES;
}
