/*
 * Copyright 2026 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package stroom.gwt.workbench.client;

import stroom.gwt.workbench.framework.client.story.Story;
import stroom.gwt.workbench.framework.client.story.StoryRegistry;

import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Objects;
import java.util.Set;

/// Compares the workbench's stories with the React Storybook's, to track the porting of the React
/// stories to GWT.
///
/// * `react-stories.json` (a test resource) - every React story, generated by
///   `test-runner/react-manifest.mjs`.
/// * `react-story-status.json` (a test resource) - React stories that won't be ported (`n/a`) or
///   can't be yet (`blocked`), each with a reason. A key is either a story id or a title, which
///   covers every story whose title is, or starts with, that title followed by `/`. Stories are
///   `ported` simply by existing in [AllStories].
///
/// [TestReactStoryCoverage] fails if the workbench has a story the React Storybook doesn't (i.e.
/// its title or export name is wrong) or the status file is invalid. Run [#main] (the Gradle task
/// `workbenchCoverage`) to print the coverage by group.
public final class ReactStoryCoverage {

    /// The resource listing every React story.
    public static final String MANIFEST_RESOURCE = "/react-stories.json";
    /// The resource giving the status of React stories that haven't been ported.
    public static final String STATUS_RESOURCE = "/react-story-status.json";
    /// The status of a React story that doesn't need a GWT port.
    public static final String NOT_APPLICABLE = "n/a";
    /// The status of a React story that can't be ported yet.
    public static final String BLOCKED = "blocked";

    private static final String LIST_OPTION = "--list=";
    private static final int GROUP_DEPTH = 2;

    private final String source;
    private final List<ReactStory> reactStories;
    private final Map<String, ReactStory> reactStoriesById = new LinkedHashMap<>();
    private final Map<String, StatusEntry> statuses;
    private final Map<String, Story> gwtStoriesById = new LinkedHashMap<>();

    /// @param source       Where the React stories came from.
    /// @param reactStories Every React story, in sidebar order.
    /// @param statuses     The status entries, keyed by story id or title.
    /// @param registry     The workbench's stories.
    public ReactStoryCoverage(final String source,
                              final List<ReactStory> reactStories,
                              final Map<String, StatusEntry> statuses,
                              final StoryRegistry registry) {
        this.source = source;
        this.reactStories = List.copyOf(reactStories);
        this.statuses = Collections.unmodifiableMap(new LinkedHashMap<>(statuses));
        reactStories.forEach(story -> reactStoriesById.put(story.id(), story));
        registry.getStories().forEach(story -> gwtStoriesById.put(story.getId(), story));
    }

    /// Loads the React stories and their status from the test resources and compares them with
    /// [AllStories].
    ///
    /// @return The coverage.
    public static ReactStoryCoverage load() {
        final ObjectMapper mapper = new ObjectMapper();
        final JsonNode manifest = readResource(mapper, MANIFEST_RESOURCE);
        final List<ReactStory> stories = new ArrayList<>();
        for (final JsonNode node : manifest.path("stories")) {
            stories.add(new ReactStory(
                    text(node, "id"),
                    text(node, "title"),
                    text(node, "name"),
                    text(node, "exportName"),
                    text(node, "file"),
                    node.has("hasPlay") && node.get("hasPlay").asBoolean()));
        }
        final Map<String, StatusEntry> statuses = new LinkedHashMap<>();
        final JsonNode statusNode = readResource(mapper, STATUS_RESOURCE).path("stories");
        for (final Entry<String, JsonNode> entry : statusNode.properties()) {
            statuses.put(entry.getKey(), new StatusEntry(
                    text(entry.getValue(), "status"),
                    text(entry.getValue(), "reason")));
        }
        return new ReactStoryCoverage(text(manifest, "source"), stories, statuses, AllStories.create());
    }

    private static String text(final JsonNode node, final String field) {
        final JsonNode value = node.get(field);
        return value == null || value.isNull()
                ? null
                : value.asString();
    }

    private static JsonNode readResource(final ObjectMapper mapper, final String resource) {
        try (final InputStream inputStream = ReactStoryCoverage.class.getResourceAsStream(resource)) {
            if (inputStream == null) {
                throw new IllegalStateException("Resource " + resource + " not found");
            }
            return mapper.readTree(inputStream);
        } catch (final IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    /// @return Every React story, in sidebar order.
    public List<ReactStory> getReactStories() {
        return reactStories;
    }

    /// @return The ids of workbench stories that aren't in the React Storybook, e.g. because their
    /// title or export name doesn't match the React story's.
    public List<String> getUnknownGwtStoryIds() {
        return gwtStoriesById.keySet()
                .stream()
                .filter(id -> !reactStoriesById.containsKey(id))
                .toList();
    }

    /// @return Problems with the status file, e.g. a key that matches no React story or a missing
    /// reason. Empty if there are none.
    public List<String> getStatusProblems() {
        final List<String> problems = new ArrayList<>();
        for (final Entry<String, StatusEntry> entry : statuses.entrySet()) {
            final String key = entry.getKey();
            final StatusEntry status = entry.getValue();
            if (reactStories.stream().noneMatch(story -> covers(key, story))) {
                problems.add("'" + key + "' is not the id or title of any React story");
            }
            if (!NOT_APPLICABLE.equals(status.status()) && !BLOCKED.equals(status.status())) {
                problems.add("'" + key + "' has status '" + status.status() + "', which should be '"
                             + NOT_APPLICABLE + "' or '" + BLOCKED + "'");
            }
            if (status.reason() == null || status.reason().isBlank()) {
                problems.add("'" + key + "' has no reason");
            }
        }
        return problems;
    }

    /// @return Differences between ported stories and their React originals that don't stop
    /// them being compared, e.g. a different display name, or a story that is ported but also
    /// has a status. Empty if there are none.
    public List<String> getWarnings() {
        final List<String> warnings = new ArrayList<>();
        for (final ReactStory react : reactStories) {
            final Story gwt = gwtStoriesById.get(react.id());
            if (gwt != null) {
                if (!react.title().equals(gwt.getTitle())) {
                    warnings.add(react.id() + ": title '" + gwt.getTitle() + "' should be '" + react.title() + "'");
                }
                if (!react.name().equals(gwt.getName())) {
                    warnings.add(react.id() + ": name '" + gwt.getName() + "' should be '" + react.name()
                                 + "' (use story(exportName, name, renderer))");
                }
                final String status = rawStatusOf(react);
                if (status != null) {
                    warnings.add(react.id() + " is ported but marked '" + status
                                 + "' in react-story-status.json");
                }
            }
        }
        return warnings;
    }

    /// @param story A React story.
    /// @return `ported`, `n/a`, `blocked` or `todo`.
    public String statusOf(final ReactStory story) {
        if (gwtStoriesById.containsKey(story.id())) {
            return "ported";
        }
        final String status = rawStatusOf(story);
        return status != null
                ? status
                : "todo";
    }

    /// @param story A React story with a play function.
    /// @return True if the workbench's story has a play function too.
    public boolean isPlayPorted(final ReactStory story) {
        final Story gwt = gwtStoriesById.get(story.id());
        return gwt != null && gwt.getPlay() != null;
    }

    private String rawStatusOf(final ReactStory story) {
        // The most specific entry wins, i.e. the story's own, then the longest title
        StatusEntry best = statuses.get(story.id());
        if (best == null) {
            int bestLength = -1;
            for (final Entry<String, StatusEntry> entry : statuses.entrySet()) {
                if (entry.getKey().contains("/") && covers(entry.getKey(), story)
                    && entry.getKey().length() > bestLength) {
                    best = entry.getValue();
                    bestLength = entry.getKey().length();
                }
            }
        }
        return best != null
                ? best.status()
                : null;
    }

    private static boolean covers(final String key, final ReactStory story) {
        return key.equals(story.id())
               || key.equals(story.title())
               || story.title().startsWith(key + "/");
    }

    /// Counts the stories in each group, i.e. each top level group and each of their children,
    /// e.g. `Widgets` and `Widgets/Buttons`, in sidebar order, followed by `Total`.
    ///
    /// @return The counts.
    public List<GroupCounts> getGroupCounts() {
        final Map<String, GroupCounts> groups = new LinkedHashMap<>();
        final GroupCounts total = new GroupCounts("Total", 0);
        for (final ReactStory story : reactStories) {
            final String[] parts = story.title().split("/");
            final StringBuilder group = new StringBuilder();
            for (int depth = 0; depth < Math.min(GROUP_DEPTH, parts.length - 1); depth++) {
                if (depth > 0) {
                    group.append('/');
                }
                group.append(parts[depth]);
                final int finalDepth = depth;
                groups.computeIfAbsent(group.toString(), name -> new GroupCounts(name, finalDepth)).add(story);
            }
            total.add(story);
        }
        final List<GroupCounts> counts = new ArrayList<>(groups.values());
        counts.add(total);
        return counts;
    }

    /// Formats a coverage report, e.g.
    /// ```
    /// Group                          React  Ported   n/a  Blocked  Todo  Done   Play  Play ported
    /// Widgets                          308       9     0        0   299    3%     90            0
    ///   Widgets/Buttons                 14       6     0        0     8   43%      2            0
    /// ```
    ///
    /// @param listPrefix If not null, the remaining stories whose id or title starts with this
    ///                   (ignoring case) are listed too, or all of them if it is empty.
    /// @return The report.
    public String report(final String listPrefix) {
        final StringBuilder sb = new StringBuilder();
        sb.append("React story coverage - ").append(reactStories.size()).append(" React stories (")
                .append(source).append(")\n\n");
        sb.append(String.format(Locale.ROOT, "%-40s %6s %7s %5s %8s %6s %5s %6s %12s%n",
                "Group", "React", "Ported", "n/a", "Blocked", "Todo", "Done", "Play", "Play ported"));
        for (final GroupCounts counts : getGroupCounts()) {
            final String name = "  ".repeat(counts.depth) + counts.name;
            sb.append(String.format(Locale.ROOT, "%-40s %6d %7d %5d %8d %6d %4d%% %6d %12d%n",
                    name, counts.react, counts.ported, counts.notApplicable, counts.blocked, counts.todo(),
                    counts.percentDone(), counts.play, counts.playPorted));
        }

        final List<String> unknown = getUnknownGwtStoryIds();
        sb.append('\n').append("Workbench stories: ").append(gwtStoriesById.size())
                .append(", not in the React Storybook: ").append(unknown.size()).append('\n');
        unknown.forEach(id -> sb.append("  ").append(id).append('\n'));
        appendList(sb, "Status file problems", getStatusProblems());
        appendList(sb, "Warnings", getWarnings());

        if (listPrefix != null) {
            final String lowerPrefix = listPrefix.toLowerCase(Locale.ROOT);
            final List<String> todo = new ArrayList<>();
            final List<String> playTodo = new ArrayList<>();
            for (final ReactStory story : reactStories) {
                if (story.id().startsWith(lowerPrefix)
                    || story.title().toLowerCase(Locale.ROOT).startsWith(lowerPrefix)) {
                    final String status = statusOf(story);
                    if ("todo".equals(status)) {
                        todo.add(story.id() + "  (" + story.file() + (story.hasPlay()
                                ? ", has play"
                                : "") + ")");
                    } else if ("ported".equals(status) && story.hasPlay() && !isPlayPorted(story)) {
                        playTodo.add(story.id() + "  (" + story.file() + ")");
                    }
                }
            }
            appendList(sb, "Remaining stories" + (listPrefix.isEmpty()
                    ? ""
                    : " matching '" + listPrefix + "'"), todo);
            appendList(sb, "Ported stories without the React play function", playTodo);
        }
        return sb.toString();
    }

    private static void appendList(final StringBuilder sb, final String heading, final List<String> items) {
        if (!items.isEmpty()) {
            sb.append('\n').append(heading).append(" (").append(items.size()).append("):\n");
            items.forEach(item -> sb.append("  ").append(item).append('\n'));
        }
    }

    /// Prints the coverage report.
    ///
    /// @param args Optionally `--list=<id or title prefix>` to list the remaining stories matching
    ///             the prefix, or `--list=` to list them all.
    public static void main(final String[] args) {
        String listPrefix = null;
        for (final String arg : args) {
            if (arg.startsWith(LIST_OPTION)) {
                listPrefix = arg.substring(LIST_OPTION.length());
            } else {
                throw new IllegalArgumentException("Unknown argument '" + arg + "'. Usage: [" + LIST_OPTION
                                                   + "<id or title prefix>]");
            }
        }
        // A report for the user to read, not logging
        System.out.print(load().report(listPrefix));
    }

    /// @return The ids of every React story.
    Set<String> getReactStoryIds() {
        return Collections.unmodifiableSet(reactStoriesById.keySet());
    }


    // --------------------------------------------------------------------------------


    /// A story in the React Storybook.
    ///
    /// @param id         The story id, e.g. `widgets-buttons-button--with-icons`.
    /// @param title      The component's title, e.g. `Widgets/Buttons/Button`.
    /// @param name       The display name, e.g. `With Icons`.
    /// @param exportName The name the story is exported as, e.g. `WithIcons`.
    /// @param file       The file defining the story.
    /// @param hasPlay    Whether it has a play function.
    public record ReactStory(String id,
                             String title,
                             String name,
                             String exportName,
                             String file,
                             boolean hasPlay) {

        /// Checks the story has the essential fields.
        public ReactStory {
            Objects.requireNonNull(id);
            Objects.requireNonNull(title);
            Objects.requireNonNull(name);
        }
    }


    // --------------------------------------------------------------------------------


    /// The status of a React story that hasn't been ported.
    ///
    /// @param status `n/a` or `blocked`.
    /// @param reason Why.
    public record StatusEntry(String status, String reason) {

    }


    // --------------------------------------------------------------------------------


    /// The counts of the stories in a group.
    public final class GroupCounts {

        private final String name;
        private final int depth;
        private int react;
        private int ported;
        private int notApplicable;
        private int blocked;
        private int play;
        private int playPorted;

        private GroupCounts(final String name, final int depth) {
            this.name = name;
            this.depth = depth;
        }

        private void add(final ReactStory story) {
            react++;
            final String status = statusOf(story);
            if ("ported".equals(status)) {
                ported++;
            } else if (NOT_APPLICABLE.equals(status)) {
                notApplicable++;
            } else if (BLOCKED.equals(status)) {
                blocked++;
            }
            if (story.hasPlay()) {
                play++;
                if (isPlayPorted(story)) {
                    playPorted++;
                }
            }
        }

        /// @return The name of the group, e.g. `Widgets/Buttons`.
        public String getName() {
            return name;
        }

        /// @return The number of React stories.
        public int getReact() {
            return react;
        }

        /// @return The number of React stories that have been ported.
        public int getPorted() {
            return ported;
        }

        /// @return The number of React stories marked `n/a`.
        public int getNotApplicable() {
            return notApplicable;
        }

        /// @return The number of React stories marked `blocked`.
        public int getBlocked() {
            return blocked;
        }

        /// @return The number of React stories still to port, i.e. not ported, `n/a` or `blocked`.
        public int todo() {
            return react - ported - notApplicable - blocked;
        }

        /// @return The number of React stories with play functions.
        public int getPlay() {
            return play;
        }

        /// @return The number of React stories with play functions whose port has one too.
        public int getPlayPorted() {
            return playPorted;
        }

        /// @return The percentage of the React stories that are ported or `n/a`, rounded down.
        public int percentDone() {
            return react == 0
                    ? 100
                    : (ported + notApplicable) * 100 / react;
        }
    }
}
