/*
 * This file is generated by jOOQ.
 */
package stroom.processor.impl.db.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.JSON;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import stroom.processor.impl.db.jooq.Keys;
import stroom.processor.impl.db.jooq.Stroom;
import stroom.processor.impl.db.jooq.tables.records.ProcessorProfileRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProcessorProfile extends TableImpl<ProcessorProfileRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>stroom.processor_profile</code>
     */
    public static final ProcessorProfile PROCESSOR_PROFILE = new ProcessorProfile();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProcessorProfileRecord> getRecordType() {
        return ProcessorProfileRecord.class;
    }

    /**
     * The column <code>stroom.processor_profile.id</code>.
     */
    public final TableField<ProcessorProfileRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>stroom.processor_profile.version</code>.
     */
    public final TableField<ProcessorProfileRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>stroom.processor_profile.create_time_ms</code>.
     */
    public final TableField<ProcessorProfileRecord, Long> CREATE_TIME_MS = createField(DSL.name("create_time_ms"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>stroom.processor_profile.create_user</code>.
     */
    public final TableField<ProcessorProfileRecord, String> CREATE_USER = createField(DSL.name("create_user"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stroom.processor_profile.update_time_ms</code>.
     */
    public final TableField<ProcessorProfileRecord, Long> UPDATE_TIME_MS = createField(DSL.name("update_time_ms"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>stroom.processor_profile.update_user</code>.
     */
    public final TableField<ProcessorProfileRecord, String> UPDATE_USER = createField(DSL.name("update_user"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stroom.processor_profile.name</code>.
     */
    public final TableField<ProcessorProfileRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stroom.processor_profile.node_group_name</code>.
     */
    public final TableField<ProcessorProfileRecord, String> NODE_GROUP_NAME = createField(DSL.name("node_group_name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stroom.processor_profile.periods</code>.
     */
    public final TableField<ProcessorProfileRecord, JSON> PERIODS = createField(DSL.name("periods"), SQLDataType.JSON, this, "");

    private ProcessorProfile(Name alias, Table<ProcessorProfileRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ProcessorProfile(Name alias, Table<ProcessorProfileRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>stroom.processor_profile</code> table reference
     */
    public ProcessorProfile(String alias) {
        this(DSL.name(alias), PROCESSOR_PROFILE);
    }

    /**
     * Create an aliased <code>stroom.processor_profile</code> table reference
     */
    public ProcessorProfile(Name alias) {
        this(alias, PROCESSOR_PROFILE);
    }

    /**
     * Create a <code>stroom.processor_profile</code> table reference
     */
    public ProcessorProfile() {
        this(DSL.name("processor_profile"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Stroom.STROOM;
    }

    @Override
    public Identity<ProcessorProfileRecord, Integer> getIdentity() {
        return (Identity<ProcessorProfileRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ProcessorProfileRecord> getPrimaryKey() {
        return Keys.KEY_PROCESSOR_PROFILE_PRIMARY;
    }

    @Override
    public List<UniqueKey<ProcessorProfileRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_PROCESSOR_PROFILE_NAME);
    }

    @Override
    public TableField<ProcessorProfileRecord, Integer> getRecordVersion() {
        return VERSION;
    }

    @Override
    public ProcessorProfile as(String alias) {
        return new ProcessorProfile(DSL.name(alias), this);
    }

    @Override
    public ProcessorProfile as(Name alias) {
        return new ProcessorProfile(alias, this);
    }

    @Override
    public ProcessorProfile as(Table<?> alias) {
        return new ProcessorProfile(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcessorProfile rename(String name) {
        return new ProcessorProfile(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcessorProfile rename(Name name) {
        return new ProcessorProfile(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcessorProfile rename(Table<?> name) {
        return new ProcessorProfile(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcessorProfile where(Condition condition) {
        return new ProcessorProfile(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcessorProfile where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcessorProfile where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcessorProfile where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProcessorProfile where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProcessorProfile where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProcessorProfile where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProcessorProfile where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcessorProfile whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcessorProfile whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
