/*
 * This file is generated by jOOQ.
 */

package stroom.activity.impl.db.jooq;


import stroom.activity.impl.db.jooq.tables.Activity;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in stroom
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>stroom.activity</code>.
     */
    public static final Activity ACTIVITY = Activity.ACTIVITY;
}
