/*
 * This file is generated by jOOQ.
 */
package stroom.auth.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import stroom.auth.db.tables.JsonWebKey;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JsonWebKeyRecord extends UpdatableRecordImpl<JsonWebKeyRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = 1425006793;

    /**
     * Setter for <code>auth.json_web_key.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>auth.json_web_key.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>auth.json_web_key.keyId</code>.
     */
    public void setKeyid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>auth.json_web_key.keyId</code>.
     */
    public String getKeyid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>auth.json_web_key.json</code>.
     */
    public void setJson(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>auth.json_web_key.json</code>.
     */
    public String getJson() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return JsonWebKey.JSON_WEB_KEY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return JsonWebKey.JSON_WEB_KEY.KEYID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return JsonWebKey.JSON_WEB_KEY.JSON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getKeyid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getJson();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getKeyid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getJson();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWebKeyRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWebKeyRecord value2(String value) {
        setKeyid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWebKeyRecord value3(String value) {
        setJson(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWebKeyRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JsonWebKeyRecord
     */
    public JsonWebKeyRecord() {
        super(JsonWebKey.JSON_WEB_KEY);
    }

    /**
     * Create a detached, initialised JsonWebKeyRecord
     */
    public JsonWebKeyRecord(Integer id, String keyid, String json) {
        super(JsonWebKey.JSON_WEB_KEY);

        set(0, id);
        set(1, keyid);
        set(2, json);
    }
}
