/*
 * This file is generated by jOOQ.
*/
package stroom.streamstore.meta.impl.db.stroom;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import stroom.streamstore.meta.impl.db.DefaultCatalog;
import stroom.streamstore.meta.impl.db.stroom.tables.Strm;
import stroom.streamstore.meta.impl.db.stroom.tables.StrmAtrKey;
import stroom.streamstore.meta.impl.db.stroom.tables.StrmAtrVal;
import stroom.streamstore.meta.impl.db.stroom.tables.StrmFeed;
import stroom.streamstore.meta.impl.db.stroom.tables.StrmProcessor;
import stroom.streamstore.meta.impl.db.stroom.tables.StrmType;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Stroom extends SchemaImpl {

    private static final long serialVersionUID = 848561374;

    /**
     * The reference instance of <code>stroom</code>
     */
    public static final Stroom STROOM = new Stroom();

    /**
     * The table <code>stroom.STRM</code>.
     */
    public final Strm STRM = stroom.streamstore.meta.impl.db.stroom.tables.Strm.STRM;

    /**
     * The table <code>stroom.STRM_ATR_KEY</code>.
     */
    public final StrmAtrKey STRM_ATR_KEY = stroom.streamstore.meta.impl.db.stroom.tables.StrmAtrKey.STRM_ATR_KEY;

    /**
     * The table <code>stroom.STRM_ATR_VAL</code>.
     */
    public final StrmAtrVal STRM_ATR_VAL = stroom.streamstore.meta.impl.db.stroom.tables.StrmAtrVal.STRM_ATR_VAL;

    /**
     * The table <code>stroom.STRM_FEED</code>.
     */
    public final StrmFeed STRM_FEED = stroom.streamstore.meta.impl.db.stroom.tables.StrmFeed.STRM_FEED;

    /**
     * The table <code>stroom.STRM_PROCESSOR</code>.
     */
    public final StrmProcessor STRM_PROCESSOR = stroom.streamstore.meta.impl.db.stroom.tables.StrmProcessor.STRM_PROCESSOR;

    /**
     * The table <code>stroom.STRM_TYPE</code>.
     */
    public final StrmType STRM_TYPE = stroom.streamstore.meta.impl.db.stroom.tables.StrmType.STRM_TYPE;

    /**
     * No further instances allowed
     */
    private Stroom() {
        super("stroom", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Strm.STRM,
            StrmAtrKey.STRM_ATR_KEY,
            StrmAtrVal.STRM_ATR_VAL,
            StrmFeed.STRM_FEED,
            StrmProcessor.STRM_PROCESSOR,
            StrmType.STRM_TYPE);
    }
}
