/*
 * This file is generated by jOOQ.
*/
package stroom.streamstore.meta.impl.db.stroom;


import javax.annotation.Generated;

import stroom.streamstore.meta.impl.db.stroom.tables.Strm;
import stroom.streamstore.meta.impl.db.stroom.tables.StrmAtrKey;
import stroom.streamstore.meta.impl.db.stroom.tables.StrmAtrVal;
import stroom.streamstore.meta.impl.db.stroom.tables.StrmFeed;
import stroom.streamstore.meta.impl.db.stroom.tables.StrmProcessor;
import stroom.streamstore.meta.impl.db.stroom.tables.StrmType;


/**
 * Convenience access to all tables in stroom
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>stroom.STRM</code>.
     */
    public static final Strm STRM = stroom.streamstore.meta.impl.db.stroom.tables.Strm.STRM;

    /**
     * The table <code>stroom.STRM_ATR_KEY</code>.
     */
    public static final StrmAtrKey STRM_ATR_KEY = stroom.streamstore.meta.impl.db.stroom.tables.StrmAtrKey.STRM_ATR_KEY;

    /**
     * The table <code>stroom.STRM_ATR_VAL</code>.
     */
    public static final StrmAtrVal STRM_ATR_VAL = stroom.streamstore.meta.impl.db.stroom.tables.StrmAtrVal.STRM_ATR_VAL;

    /**
     * The table <code>stroom.STRM_FEED</code>.
     */
    public static final StrmFeed STRM_FEED = stroom.streamstore.meta.impl.db.stroom.tables.StrmFeed.STRM_FEED;

    /**
     * The table <code>stroom.STRM_PROCESSOR</code>.
     */
    public static final StrmProcessor STRM_PROCESSOR = stroom.streamstore.meta.impl.db.stroom.tables.StrmProcessor.STRM_PROCESSOR;

    /**
     * The table <code>stroom.STRM_TYPE</code>.
     */
    public static final StrmType STRM_TYPE = stroom.streamstore.meta.impl.db.stroom.tables.StrmType.STRM_TYPE;
}
