/*
 * Copyright 2016-2025 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */
package stroom.gitrepo.impl.db.jooq.tables.records;


import stroom.gitrepo.impl.db.jooq.tables.GitRepo;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GitRepoRecord extends UpdatableRecordImpl<GitRepoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>stroom.git_repo.git_repo_uuid</code>.
     */
    public void setGitRepoUuid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>stroom.git_repo.git_repo_uuid</code>.
     */
    public String getGitRepoUuid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>stroom.git_repo.git_commit_hash</code>.
     */
    public void setGitCommitHash(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>stroom.git_repo.git_commit_hash</code>.
     */
    public String getGitCommitHash() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GitRepoRecord
     */
    public GitRepoRecord() {
        super(GitRepo.GIT_REPO);
    }

    /**
     * Create a detached, initialised GitRepoRecord
     */
    public GitRepoRecord(String gitRepoUuid, String gitCommitHash) {
        super(GitRepo.GIT_REPO);

        setGitRepoUuid(gitRepoUuid);
        setGitCommitHash(gitCommitHash);
        resetChangedOnNotNull();
    }
}
