/*
 * Copyright 2016-2025 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */
package stroom.annotation.impl.db.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import stroom.annotation.impl.db.jooq.tables.Annotation;
import stroom.annotation.impl.db.jooq.tables.AnnotationDataLink;
import stroom.annotation.impl.db.jooq.tables.AnnotationEntry;
import stroom.annotation.impl.db.jooq.tables.AnnotationFeed;
import stroom.annotation.impl.db.jooq.tables.AnnotationLink;
import stroom.annotation.impl.db.jooq.tables.AnnotationSubscription;
import stroom.annotation.impl.db.jooq.tables.AnnotationTag;
import stroom.annotation.impl.db.jooq.tables.AnnotationTagLink;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Stroom extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>stroom</code>
     */
    public static final Stroom STROOM = new Stroom();

    /**
     * The table <code>stroom.annotation</code>.
     */
    public final Annotation ANNOTATION = Annotation.ANNOTATION;

    /**
     * The table <code>stroom.annotation_data_link</code>.
     */
    public final AnnotationDataLink ANNOTATION_DATA_LINK = AnnotationDataLink.ANNOTATION_DATA_LINK;

    /**
     * The table <code>stroom.annotation_entry</code>.
     */
    public final AnnotationEntry ANNOTATION_ENTRY = AnnotationEntry.ANNOTATION_ENTRY;

    /**
     * The table <code>stroom.annotation_feed</code>.
     */
    public final AnnotationFeed ANNOTATION_FEED = AnnotationFeed.ANNOTATION_FEED;

    /**
     * The table <code>stroom.annotation_link</code>.
     */
    public final AnnotationLink ANNOTATION_LINK = AnnotationLink.ANNOTATION_LINK;

    /**
     * The table <code>stroom.annotation_subscription</code>.
     */
    public final AnnotationSubscription ANNOTATION_SUBSCRIPTION = AnnotationSubscription.ANNOTATION_SUBSCRIPTION;

    /**
     * The table <code>stroom.annotation_tag</code>.
     */
    public final AnnotationTag ANNOTATION_TAG = AnnotationTag.ANNOTATION_TAG;

    /**
     * The table <code>stroom.annotation_tag_link</code>.
     */
    public final AnnotationTagLink ANNOTATION_TAG_LINK = AnnotationTagLink.ANNOTATION_TAG_LINK;

    /**
     * No further instances allowed
     */
    private Stroom() {
        super("stroom", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Annotation.ANNOTATION,
            AnnotationDataLink.ANNOTATION_DATA_LINK,
            AnnotationEntry.ANNOTATION_ENTRY,
            AnnotationFeed.ANNOTATION_FEED,
            AnnotationLink.ANNOTATION_LINK,
            AnnotationSubscription.ANNOTATION_SUBSCRIPTION,
            AnnotationTag.ANNOTATION_TAG,
            AnnotationTagLink.ANNOTATION_TAG_LINK
        );
    }
}
