package stroom.refdata.offheapstore.serdes;

import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.Serializer;
import com.esotericsoftware.kryo.io.Input;
import com.esotericsoftware.kryo.io.Output;

import java.util.UUID;

/**
 * Kryo serializer for a string representation of a {@link UUID}. The string form must
 * conform to the output generated by {@link UUID#toString()}. May use variable length
 * serialisation.
 */
class UUIDKryoSerializer extends Serializer<String> {

    @Override
    public void write(final Kryo kryo, final Output output, final String uuidStr) {
        UUID uuid = UUID.fromString(uuidStr);
        output.writeLong(uuid.getMostSignificantBits(), false);
        output.writeLong(uuid.getLeastSignificantBits(), false);
    }

    @Override
    public String read(final Kryo kryo, final Input input, final Class<String> type) {
        final long uuidHighBits = input.readLong(false);
        final long uuidLowBits = input.readLong(false);
        return new UUID(uuidHighBits, uuidLowBits).toString();
    }
}
