@startuml

' avoid problems with angled crows feet
skinparam linetype ortho

entity source {
  *id : bigint
  --
  *path : varchar(255) - unique
  *feed_name : varchar(255)
  *type_name : varchar(255)
  *last_modified_time_ms : bigint
  *examined : boolean
  *forwarded : boolean
  *new_position : bigint
}

entity source_item {
  *id : bigint
  --
  *name : varchar(255)
  *feed_name : varchar(255)
  *type_name : varchar(255)
  *byte_size : bigint
  *fk_source_id : bigint
  *fk_aggregate_id : bigint
  *new_position : bigint
}

entity source_entry {
  *id : bigint
  --
  *extension : varchar(255)
  *extension_type : int
  *byte_size : bigint
  *fk_source_item_id : bigint
}

entity aggregate {
  *id : bigint
  --
  *create_time_ms : bigint
  *feed_name : varchar(255)
  *type_name : varchar(255)
  *byte_size : bigint
  *items : int
  *complete : boolean
  *new_position : bigint
}

entity forward_url {
  *id : int
  --
  *url : varchar(255)
}

entity forward_source {
  *id : bigint
  --
  *update_time_ms : bigint
  *fk_forward_url_id : int
  *fk_source_id : bigint
  *success : boolean
  *error : varchar(255)
  *tries : bigint
  *new_position : bigint
  *retry_position : bigint
}

entity forward_aggregate {
  *id : bigint
  --
  *update_time_ms : bigint
  *fk_forward_url_id : int
  *fk_aggregate_id : bigint
  *success : boolean
  *error : varchar(255)
  *tries : bigint
  *new_position : bigint
  *retry_position : bigint
}

source ||..o{ source_item
source_item ||--|{ source_entry
aggregate ||--|{ source_item
forward_source }o--|| forward_url
forward_source }o..|| source
forward_aggregate }o--|| forward_url
forward_aggregate }o--|| aggregate

@enduml