@startuml

' avoid problems with angled crows feet
skinparam linetype ortho

entity feed {
  *id : bigint
  --
  *feed_name : varchar(255)
  *type_name : varchar(255)
}

entity source {
  *id : bigint
  --
  *path : varchar(255) - unique
  *fk_feed_id : bigint
  *examined : boolean
  *item_count : integer
  *new_position : bigint
}

feed ||--|{ source

@enduml