package stroom.authentication;

public enum LoginResult {
    GOOD_CREDENTIALS,
    BAD_CREDENTIALS,
    LOCKED_BAD_CREDENTIALS,
    LOCKED_GOOD_CREDENTIALS,
    DISABLED_BAD_CREDENTIALS,
    DISABLED_GOOD_CREDENTIALS,
    USER_DOES_NOT_EXIST,
    INACTIVE_GOOD_CREDENTIALS,
    INACTIVE_BAD_CREDENTIALS;
}
