/*
 * Copyright 2016 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

DROP TABLE ANAL_OUT_DAT_SRC;
--DROP TABLE STATE_DAT_SRC;

ALTER TABLE FOLDER              DROP FOREIGN KEY FK_FOLDER_ID;
ALTER TABLE DICT                DROP FOREIGN KEY DICT_FK_FOLDER_ID;
ALTER TABLE FD                  DROP FOREIGN KEY FD_FK_FOLDER_ID;
ALTER TABLE IDX                 DROP FOREIGN KEY IDX_FK_FOLDER_ID;
ALTER TABLE PIPE                DROP FOREIGN KEY PIPE_FK_FOLDER_ID;
ALTER TABLE TXT_CONV            DROP FOREIGN KEY TXT_CONV_FK_FOLDER_ID;
ALTER TABLE XML_SCHEMA          DROP FOREIGN KEY XML_SCHEMA_FK_FOLDER_ID;
ALTER TABLE XSLT                DROP FOREIGN KEY XSLT_FK_FOLDER_ID;
ALTER TABLE DASH                DROP FOREIGN KEY DASH_FK_FOLDER_ID;
ALTER TABLE SCRIPT              DROP FOREIGN KEY SCRIPT_FK_FOLDER_ID;
ALTER TABLE VIS                 DROP FOREIGN KEY VIS_FK_FOLDER_ID;
ALTER TABLE STAT_DAT_SRC        DROP FOREIGN KEY STAT_DAT_SRC_FK_FOLDER_ID;
ALTER TABLE STATE_DAT_SRC       DROP FOREIGN KEY STATE_DAT_SRC_FK_FOLDER_ID;
ALTER TABLE STROOM_STATS_STORE  DROP FOREIGN KEY STROOM_STATS_STORE_FK_FOLDER_ID;

ALTER TABLE FOLDER              DROP INDEX NAME;
ALTER TABLE DICT                DROP INDEX NAME;
ALTER TABLE IDX                 DROP INDEX NAME;
ALTER TABLE PIPE                DROP INDEX NAME;
ALTER TABLE TXT_CONV            DROP INDEX NAME;
ALTER TABLE XML_SCHEMA          DROP INDEX NAME;
ALTER TABLE XSLT                DROP INDEX NAME;
ALTER TABLE DASH                DROP INDEX NAME;
ALTER TABLE SCRIPT              DROP INDEX NAME;
ALTER TABLE VIS                 DROP INDEX NAME;

ALTER TABLE FOLDER              DROP COLUMN FK_FOLDER_ID;
ALTER TABLE DICT                DROP COLUMN FK_FOLDER_ID;
ALTER TABLE IDX                 DROP COLUMN FK_FOLDER_ID;
ALTER TABLE FD                  DROP COLUMN FK_FOLDER_ID;
ALTER TABLE PIPE                DROP COLUMN FK_FOLDER_ID;
ALTER TABLE TXT_CONV            DROP COLUMN FK_FOLDER_ID;
ALTER TABLE XML_SCHEMA          DROP COLUMN FK_FOLDER_ID;
ALTER TABLE XSLT                DROP COLUMN FK_FOLDER_ID;
ALTER TABLE DASH                DROP COLUMN FK_FOLDER_ID;
ALTER TABLE SCRIPT              DROP COLUMN FK_FOLDER_ID;
ALTER TABLE VIS                 DROP COLUMN FK_FOLDER_ID;
ALTER TABLE STAT_DAT_SRC        DROP COLUMN FK_FOLDER_ID;
ALTER TABLE STATE_DAT_SRC       DROP COLUMN FK_FOLDER_ID;
ALTER TABLE STROOM_STATS_STORE  DROP COLUMN FK_FOLDER_ID;

-- Elastic Search Indexing
CREATE TABLE ELASTIC_INDEX (
  ID 				int(11) NOT NULL AUTO_INCREMENT,
  VER				tinyint(4) NOT NULL,
  CRT_MS 			bigint NULL DEFAULT NULL,
  CRT_USER			varchar(255) DEFAULT NULL,
  UPD_MS 			bigint NULL DEFAULT NULL,
  UPD_USER 			varchar(255) DEFAULT NULL,
  NAME 				varchar(255) NOT NULL,
  UUID              varchar(255) NOT NULL,
  PRIMARY KEY       (ID),
  UNIQUE            (UUID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE ANNOTATIONS_INDEX (
  ID 				int(11) NOT NULL AUTO_INCREMENT,
  VER				tinyint(4) NOT NULL,
  CRT_MS 			bigint NULL DEFAULT NULL,
  CRT_USER			varchar(255) DEFAULT NULL,
  UPD_MS 			bigint NULL DEFAULT NULL,
  UPD_USER 			varchar(255) DEFAULT NULL,
  NAME 				varchar(255) NOT NULL,
  UUID              varchar(255) NOT NULL,
  PRIMARY KEY       (ID),
  UNIQUE            (UUID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE FOLDER;