server:
  applicationContextPath: ${APPLICATION_CONTEXT_PATH:- /}
  adminContextPath: ${ADMIN_CONTEXT_PATH:- /stroomAdmin}
  applicationConnectors:
    - type: http
      port: ${STROOM_APP_PORT:-8080}
      useForwardedHeaders: true
  adminConnectors:
    - type: http
      port: ${STROOM_ADMIN_PORT:-8081}
      useForwardedHeaders: true
  detailedJsonProcessingExceptionMapper: true
  requestLog:
    appenders:
      - type: file
        currentLogFilename: logs/access/access.log
        threshold: ALL
        queueSize: 256
        discardingThreshold: 0
        archive: true
        archivedLogFilenamePattern: logs/access/access-%d{yyyy-MM-dd'T'HH:mm}.log
        archivedFileCount: 10
        timeZone: UTC

logging:
  level: ${STROOM_LOGGING_LEVEL:- ERROR}
  loggers:
    stroom: INFO
    io.dropwizard: ERROR
    org.eclipse.jetty: ERROR
    org.glassfish: ERROR
    org.glassfish.jersey: ERROR
    #    stroom.app.logging.DefaultLoggingFilter: INFO
    #    org.glassfish.jersey.logging.LoggingFeature: INFO
    #    org.glassfish.jersey.server.ServerRuntime.Responder: INFO
    #    org.glassfish.jersey.server.validation.internal.ValidationExceptionMapper: FINER
    org.flywaydb: ERROR
    "event-logger":
      level: INFO
      additive: false
      appenders:
        - type: file
          currentLogFilename: logs/user/user.log
          threshold: ALL
          queueSize: 256
          discardingThreshold: 0
          archive: true
          archivedLogFilenamePattern: logs/user/user-%d{yyyy-MM-dd'T'HH:mm}.log
          archivedFileCount: 10
          timeZone: UTC
          logFormat: "%msg%n"

  #    "search_progress_trace":
  #      level: TRACE
  #      additive: false
  #      appenders:
  #        - type: file
  #          currentLogFilename: logs/search/search_progress_trace.csv
  #          threshold: ALL
  #          queueSize: 250
  #          discardingThreshold: 0
  #          archive: false
  #          archivedLogFilenamePattern: logs/search/search_progress_trace-%d{yyyy-MM-dd'T'HH:mm}.csv
  #          archivedFileCount: 0
  #          timeZone: UTC
  #          logFormat: "%msg%n"

  appenders:
    - type: console
      logFormat: "%highlight(%-5level) %d{\"yyyy-MM-dd'T'HH:mm:ss.SSS'Z'\",UTC} %yellow(%thread) %cyan(%-30logger{25}) %msg %n"
      timeZone: UTC
    - type: file
      currentLogFilename: logs/app/app.log
      threshold: ALL
      queueSize: 256
      discardingThreshold: 0
      archive: true
      archivedLogFilenamePattern: logs/app/app-%d{yyyy-MM-dd'T'HH:mm}.log
      archivedFileCount: 10
      timeZone: UTC
      logFormat: "%-6level [%d{\"yyyy-MM-dd'T'HH:mm:ss.SSS'Z'\",UTC}] [%t] %logger - %X{code} %msg %n"

jerseyClients:
  OPEN_ID:
    # KeyCloak and Azure AD don't like gzip encoded requests
    gzipEnabledForRequests: false

appConfig:
  commonDbDetails:
    connection:
      jdbcDriverUrl: ${STROOM_JDBC_DRIVER_URL:-jdbc:mysql://localhost:3307/stroom?useUnicode=yes&characterEncoding=UTF-8}
      jdbcDriverUsername: ${STROOM_JDBC_DRIVER_USERNAME:-stroomuser}
      jdbcDriverPassword: ${STROOM_JDBC_DRIVER_PASSWORD:-stroompassword1}
  contentPackImport:
    enabled: true
  job:
    enabled: true
    enableJobsOnBootstrap: true
    executionInterval: "10s"
  node:
    name: node1a
  path:
    # Versioned dirs for dev to allow running multiple stroom instances
    home: "${STROOM_HOME:-~/.stroom/v7/node1a}"
    temp: "${STROOM_TEMP:-/tmp/stroom/v7/node1a}"
  planb:
    nodeList: [ node2a ]
  # Comment out the publicUri block if you are not running with nginx
  publicUri:
    hostname: ${API_GATEWAY_HOST:-localhost}
    port: ${API_GATEWAY_PORT:-}
  security:
    identity:
      autoCreateAdminAccountOnBoot: true
      passwordPolicy:
        minimumPasswordStrength: 1
        minimumPasswordLength: 1
    authentication:
      openId:
        identityProviderType: ${IDP_TYPE:-TEST_CREDENTIALS}

  statistics:
    hbase:
      # UUID of the Kafka Config Doc that is created by Setup Sample Data
      # Debatable if the doc should be added to a content pack or not
      kafkaConfigUuid: 7cbf9153-869c-43bb-a316-1c652673e680
    internal:
      enabledStoreTypes: ${STROOM_ENABLED_STAT_STORE_TYPES:-[ "StatisticStore" ]}
#      enabledStoreTypes: ${STROOM_ENABLED_STAT_STORE_TYPES:-[ "StatisticStore", "StroomStatsStore" ]}

