/*
 * Copyright 2016-2025 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package stroom.util.authentication;

/**
 * A set of hard-coded credentials for use ONLY in testing. They allow us to run
 * stroom and stroom-proxy such that API calls from proxy to stroom will pass
 * authentication out of the box.
 * <p>
 * The values used in the this class are generated by the main() method in
 * {@link stroom.authentication.oauth2.GenerateTestOpenIdDetails}
 * <p>
 * These default values will only be used if the following prop is set to true
 * {@link stroom.authentication.config.AuthenticationConfig#isUseDefaultOpenIdCredentials()}
 */
@SuppressWarnings("checkstyle:LineLength")
public class DefaultOpenIdCredentials {

    // Made with a public ctor, so it is injectable and mockable, if required.
    public DefaultOpenIdCredentials() {
    }

    // ==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--
    // ALL the content between these dashed lines was generated and inserted using
    // stroom.security.identity.openid.GenerateTestOpenIdDetails at 2022-12-13T18:22:59.731961911Z
    // The dashed lines are important, don't remove them!
    private static final String OAUTH2_ISSUER = "default-test-only-issuer";
    private static final String OAUTH2_CLIENT_ID = "ByUuXPEUBwqVfAm9Ztr9K12NhqWyMFz1TmXSlWyP.client-id.apps.stroom-idp";
    private static final String OAUTH2_CLIENT_NAME = "Stroom Client Internal (TEST ONLY)";
    private static final String OAUTH2_CLIENT_SECRET = "giUDCvweJb3EKC1aYCWSdYMCjmduBVBzhhKVNyFh.client-secret.apps.stroom-idp";
    private static final String OAUTH2_CLIENT_URI_PATTERN = ".*";
    private static final String PUBLIC_KEY_ID = "f3742e0e-d6e4-46ea-82c4-0fda4219e992";
    private static final String PUBLIC_KEY_JSON = "{\"kty\":\"RSA\",\"kid\":\"f3742e0e-d6e4-46ea-82c4-0fda4219e992\",\"use\":\"sig\",\"alg\":\"RS256\",\"n\":\"ugYeiAFbcdaincP3hM709wlIO16THr758roosZ_K22P5AjEaK85Sf4A-cKYNfWB8R2-gOC3UCJycFAjGiu3yfhzsGO8-3jRSCbvB5GPUZnU1bplh0o6EA2stVSdahU4nyH07h6vBGbz9g6WSut80B2R875NiVQ-LnYs_JgckgzGFDAeU8xJm7gXvKLZZMyam6nBXv9hKM8Urm5xxgVv5nIe21V0IuiUSsKzMH5U2hMo_hjudDlQH1rwZBHTikG274AK7qIGJDPIVt5YTmEGqh-MsDLwEjCeGzMLXFqoZJO1sYu7efda1ZsZ_GgXCUlnQUh--r6_7w-k_59tXbavnrw\",\"e\":\"AQAB\",\"d\":\"CbLx-pNfijLvrZwfFqyXtx2jx3yp3QuGCrLMFl7He-Ldg9C9lZUfVgiAuOzffS7_q9XVG7i_-mb3-E9w0qOPZiXp5W7r7zf5IwrIFDlkRKdNzuNuZ0UI-wimh28S2Cp4BosJBIze95GUAj4qxVWH5-7EWNVtZhP2apNtCnWK4NAoZFVnsP8EpvdTu0ptX3mTPQuqpovRrBjg1mCvkc--agp8XoQpSMMLnGGVO-xflFqKUZIsB-jAn13XAEZljacAdSNhC6fvaHLiw04uaQ5gncx_BrbuKynna8ndT25Af0TIYNKJWp5KeEwaZzhQ1azzcNXPCf3eJiNhldZijQA-cQ\",\"p\":\"4RX-i526vSj75r1w3A6z_I0PaXJNS5Q3seFTP-vBgnzP2E3bA8YVjcMrjMRWYbHwZ-ygSxC6GRP8vZx9b5h3eeEENGKGVxVK-bmQ3oLxWG7ivFP1MEiDEaQDjewHqkM_s6Mp012XzyWNevedjC7CNqYHJpxP5_pOfFLEhIwHt-k\",\"q\":\"05K1DL_mVhX0LdUe7jQI-buibux8qytPq_rAno4Wg-BYBDa0dIOoGjXc0_V1j1GbFYzVaai71NRk06SyT62GeDoxYo9nX8oUZqw2YDgXoZL2VdvXnrCR6KIYbsEH4St0D2K53gNHSKercNGD2knRNGWnLOF8Yubu61kn4FaH-9c\",\"dp\":\"HcDBiAUOhSigu6x4-a273vtqeR7R1ta90faeAYoRZ0VGWCpadBJAESAmZpIhdQKHa8Vcnu-UGfKJayr_bbvytxqmaqJHbcVzxrTf0Hnwmyb1M73JYFuFb9SFX8I-dSQ0jHNZ-QWbJpepLwMCQWCA7aZetZzd9yUgMNDkBz1XW9k\",\"dq\":\"Xshqs7uExSwwqBfCM5S8MKUOsALiFwzgNHuxr1aYX5wx0jFvxoL03EklFQ_yCrLUd2MQeLVO8Jn2UZqHB4sFovbvCOiVtyQg355m_dQjQg9ErFJA1qbjtwRnTbbMgOOmqv3fpsZxOOtksrYqC7DmOEMSEdkykFxEzMq0QpyBbyE\",\"qi\":\"tHDqZT1jFaH65bvJKW1dEzwiQXpllNLSWpYHiv3BGOU1CBHnGynz6smDA9Fe-KR5T9gV6R3Qfk6purOVSRyjvFpF2OsPPMGGwH0j0F69eJ6AK-6rQs2s58wLHZNTswTnPHT8Js2ieGapQOi5mDywqYIgoB0AIQchNDXLkHaVzNg\"}";
    private static final String API_KEY_USER_EMAIL = "default-test-only-api-key-user";
    private static final String API_KEY = "eyJhbGciOiJSUzI1NiIsImtpZCI6ImYzNzQyZTBlLWQ2ZTQtNDZlYS04MmM0LTBmZGE0MjE5ZTk5MiJ9.eyJleHAiOjIzMDIxMDc3NzksInN1YiI6ImRlZmF1bHQtdGVzdC1vbmx5LWFwaS1rZXktdXNlciIsImlzcyI6ImRlZmF1bHQtdGVzdC1vbmx5LWlzc3VlciIsImF1ZCI6IkJ5VXVYUEVVQndxVmZBbTladHI5SzEyTmhxV3lNRnoxVG1YU2xXeVAuY2xpZW50LWlkLmFwcHMuc3Ryb29tLWlkcCJ9.pvP3ojlYnbjpRdvuRcj7R9gbTgb-pirCDwGwPTWrDa4MTb30IS0DRNi6wdBL6K4FQJVwOwkRsc3xBIhF2cRAxLgZ1qWr7Zeh0bGB25y1womshnDvFQQFsl6vM-taxSRXrZ2b8by7KbDu9-PitxIaLssD9ZDe9hoi5vZlWlVUe6CI3EfUCQGcyqbVPrkwPpWg_tQa6Mvx7UxUf_GslYt6YVibF8FVelM5ISVZEZRM8GRUTeoKZGSySiFR18CzUn7XsRpffEtmwpo8JuEoOprvgPk-n8y6nQfZnPCdr45bthTi4tzARPTCLaK0XUiiAP58_LfaeldjMhSdYnefgT3gXg";
    // ==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--


    public String getOauth2Issuer() {
        return OAUTH2_ISSUER;
    }

    public String getOauth2ClientId() {
        return OAUTH2_CLIENT_ID;
    }

    public String getOauth2ClientName() {
        return OAUTH2_CLIENT_NAME;
    }

    public String getOauth2ClientSecret() {
        return OAUTH2_CLIENT_SECRET;
    }

    public String getOauth2ClientUriPattern() {
        return OAUTH2_CLIENT_URI_PATTERN;
    }

    public String getPublicKeyId() {
        return PUBLIC_KEY_ID;
    }

    public String getPublicKeyJson() {
        return PUBLIC_KEY_JSON;
    }

    public String getApiKeyUserEmail() {
        return API_KEY_USER_EMAIL;
    }

    public String getApiKey() {
        return API_KEY;
    }
}
