ALTER TABLE SCRIPT ADD COLUMN DAT longtext;
UPDATE SCRIPT s SET DAT = (SELECT DAT FROM RES WHERE ID = s.FK_RES_ID);
ALTER TABLE SCRIPT DROP FOREIGN KEY SCRIPT_FK_RES_ID;
ALTER TABLE SCRIPT DROP COLUMN FK_RES_ID;
