/*
 * This file is generated by jOOQ.
 */
package stroom.explorer.impl.db.jooq.tables.records;


import org.jooq.Record3;
import org.jooq.impl.UpdatableRecordImpl;

import stroom.explorer.impl.db.jooq.tables.TabSessionDocRef;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TabSessionDocRefRecord extends UpdatableRecordImpl<TabSessionDocRefRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>stroom.tab_session_doc_ref.tab_session_id</code>.
     */
    public void setTabSessionId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>stroom.tab_session_doc_ref.tab_session_id</code>.
     */
    public Integer getTabSessionId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>stroom.tab_session_doc_ref.tab_index</code>.
     */
    public void setTabIndex(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>stroom.tab_session_doc_ref.tab_index</code>.
     */
    public Integer getTabIndex() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>stroom.tab_session_doc_ref.doc_ref_type</code>.
     */
    public void setDocRefType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>stroom.tab_session_doc_ref.doc_ref_type</code>.
     */
    public String getDocRefType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>stroom.tab_session_doc_ref.doc_ref_id</code>.
     */
    public void setDocRefId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>stroom.tab_session_doc_ref.doc_ref_id</code>.
     */
    public String getDocRefId() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<Integer, String, String> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TabSessionDocRefRecord
     */
    public TabSessionDocRefRecord() {
        super(TabSessionDocRef.TAB_SESSION_DOC_REF);
    }

    /**
     * Create a detached, initialised TabSessionDocRefRecord
     */
    public TabSessionDocRefRecord(Integer tabSessionId, Integer tabIndex, String docRefType, String docRefId) {
        super(TabSessionDocRef.TAB_SESSION_DOC_REF);

        setTabSessionId(tabSessionId);
        setTabIndex(tabIndex);
        setDocRefType(docRefType);
        setDocRefId(docRefId);
        resetChangedOnNotNull();
    }
}
