/*
 * This file is generated by jOOQ.
 */
package stroom.security.identity.db.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import stroom.security.identity.db.jooq.tables.records.OauthClientRecord;
import stroom.security.identity.db.jooq.Indexes;
import stroom.security.identity.db.jooq.Keys;
import stroom.security.identity.db.jooq.Stroom;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OauthClient extends TableImpl<OauthClientRecord> {

    private static final long serialVersionUID = -1970296834;

    /**
     * The reference instance of <code>stroom.oauth_client</code>
     */
    public static final OauthClient OAUTH_CLIENT = new OauthClient();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OauthClientRecord> getRecordType() {
        return OauthClientRecord.class;
    }

    /**
     * The column <code>stroom.oauth_client.id</code>.
     */
    public final TableField<OauthClientRecord, Integer> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>stroom.oauth_client.version</code>.
     */
    public final TableField<OauthClientRecord, Integer> VERSION = createField(DSL.name("version"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>stroom.oauth_client.create_time_ms</code>.
     */
    public final TableField<OauthClientRecord, Long> CREATE_TIME_MS = createField(DSL.name("create_time_ms"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>stroom.oauth_client.create_user</code>.
     */
    public final TableField<OauthClientRecord, String> CREATE_USER = createField(DSL.name("create_user"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stroom.oauth_client.update_time_ms</code>.
     */
    public final TableField<OauthClientRecord, Long> UPDATE_TIME_MS = createField(DSL.name("update_time_ms"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>stroom.oauth_client.update_user</code>.
     */
    public final TableField<OauthClientRecord, String> UPDATE_USER = createField(DSL.name("update_user"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stroom.oauth_client.name</code>.
     */
    public final TableField<OauthClientRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stroom.oauth_client.client_id</code>.
     */
    public final TableField<OauthClientRecord, String> CLIENT_ID = createField(DSL.name("client_id"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stroom.oauth_client.client_secret</code>.
     */
    public final TableField<OauthClientRecord, String> CLIENT_SECRET = createField(DSL.name("client_secret"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stroom.oauth_client.uri_pattern</code>.
     */
    public final TableField<OauthClientRecord, String> URI_PATTERN = createField(DSL.name("uri_pattern"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>stroom.oauth_client</code> table reference
     */
    public OauthClient() {
        this(DSL.name("oauth_client"), null);
    }

    /**
     * Create an aliased <code>stroom.oauth_client</code> table reference
     */
    public OauthClient(String alias) {
        this(DSL.name(alias), OAUTH_CLIENT);
    }

    /**
     * Create an aliased <code>stroom.oauth_client</code> table reference
     */
    public OauthClient(Name alias) {
        this(alias, OAUTH_CLIENT);
    }

    private OauthClient(Name alias, Table<OauthClientRecord> aliased) {
        this(alias, aliased, null);
    }

    private OauthClient(Name alias, Table<OauthClientRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> OauthClient(Table<O> child, ForeignKey<O, OauthClientRecord> key) {
        super(child, key, OAUTH_CLIENT);
    }

    @Override
    public Schema getSchema() {
        return Stroom.STROOM;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.OAUTH_CLIENT_CLIENT_ID, Indexes.OAUTH_CLIENT_NAME, Indexes.OAUTH_CLIENT_PRIMARY);
    }

    @Override
    public Identity<OauthClientRecord, Integer> getIdentity() {
        return Keys.IDENTITY_OAUTH_CLIENT;
    }

    @Override
    public UniqueKey<OauthClientRecord> getPrimaryKey() {
        return Keys.KEY_OAUTH_CLIENT_PRIMARY;
    }

    @Override
    public List<UniqueKey<OauthClientRecord>> getKeys() {
        return Arrays.<UniqueKey<OauthClientRecord>>asList(Keys.KEY_OAUTH_CLIENT_PRIMARY, Keys.KEY_OAUTH_CLIENT_NAME, Keys.KEY_OAUTH_CLIENT_CLIENT_ID);
    }

    @Override
    public TableField<OauthClientRecord, Integer> getRecordVersion() {
        return VERSION;
    }

    @Override
    public OauthClient as(String alias) {
        return new OauthClient(DSL.name(alias), this);
    }

    @Override
    public OauthClient as(Name alias) {
        return new OauthClient(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OauthClient rename(String name) {
        return new OauthClient(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OauthClient rename(Name name) {
        return new OauthClient(name, null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, Integer, Long, String, Long, String, String, String, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }
}
