/*
 * This file is generated by jOOQ.
 */
package stroom.index.impl.db.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import stroom.index.impl.db.jooq.Indexes;
import stroom.index.impl.db.jooq.Keys;
import stroom.index.impl.db.jooq.Stroom;
import stroom.index.impl.db.jooq.tables.IndexVolume.IndexVolumePath;
import stroom.index.impl.db.jooq.tables.records.IndexShardRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class IndexShard extends TableImpl<IndexShardRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>stroom.index_shard</code>
     */
    public static final IndexShard INDEX_SHARD = new IndexShard();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IndexShardRecord> getRecordType() {
        return IndexShardRecord.class;
    }

    /**
     * The column <code>stroom.index_shard.id</code>.
     */
    public final TableField<IndexShardRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>stroom.index_shard.node_name</code>.
     */
    public final TableField<IndexShardRecord, String> NODE_NAME = createField(DSL.name("node_name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stroom.index_shard.fk_volume_id</code>.
     */
    public final TableField<IndexShardRecord, Integer> FK_VOLUME_ID = createField(DSL.name("fk_volume_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>stroom.index_shard.index_uuid</code>.
     */
    public final TableField<IndexShardRecord, String> INDEX_UUID = createField(DSL.name("index_uuid"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stroom.index_shard.commit_document_count</code>.
     */
    public final TableField<IndexShardRecord, Integer> COMMIT_DOCUMENT_COUNT = createField(DSL.name("commit_document_count"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>stroom.index_shard.commit_duration_ms</code>.
     */
    public final TableField<IndexShardRecord, Long> COMMIT_DURATION_MS = createField(DSL.name("commit_duration_ms"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stroom.index_shard.commit_ms</code>.
     */
    public final TableField<IndexShardRecord, Long> COMMIT_MS = createField(DSL.name("commit_ms"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stroom.index_shard.document_count</code>.
     */
    public final TableField<IndexShardRecord, Integer> DOCUMENT_COUNT = createField(DSL.name("document_count"), SQLDataType.INTEGER.defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>stroom.index_shard.file_size</code>.
     */
    public final TableField<IndexShardRecord, Long> FILE_SIZE = createField(DSL.name("file_size"), SQLDataType.BIGINT.defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>stroom.index_shard.status</code>.
     */
    public final TableField<IndexShardRecord, Byte> STATUS = createField(DSL.name("status"), SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>stroom.index_shard.index_version</code>.
     */
    public final TableField<IndexShardRecord, String> INDEX_VERSION = createField(DSL.name("index_version"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>stroom.index_shard.partition_name</code>.
     */
    public final TableField<IndexShardRecord, String> PARTITION_NAME = createField(DSL.name("partition_name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stroom.index_shard.partition_from_ms</code>.
     */
    public final TableField<IndexShardRecord, Long> PARTITION_FROM_MS = createField(DSL.name("partition_from_ms"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stroom.index_shard.partition_to_ms</code>.
     */
    public final TableField<IndexShardRecord, Long> PARTITION_TO_MS = createField(DSL.name("partition_to_ms"), SQLDataType.BIGINT, this, "");

    private IndexShard(Name alias, Table<IndexShardRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private IndexShard(Name alias, Table<IndexShardRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>stroom.index_shard</code> table reference
     */
    public IndexShard(String alias) {
        this(DSL.name(alias), INDEX_SHARD);
    }

    /**
     * Create an aliased <code>stroom.index_shard</code> table reference
     */
    public IndexShard(Name alias) {
        this(alias, INDEX_SHARD);
    }

    /**
     * Create a <code>stroom.index_shard</code> table reference
     */
    public IndexShard() {
        this(DSL.name("index_shard"), null);
    }

    public <O extends Record> IndexShard(Table<O> path, ForeignKey<O, IndexShardRecord> childPath, InverseForeignKey<O, IndexShardRecord> parentPath) {
        super(path, childPath, parentPath, INDEX_SHARD);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class IndexShardPath extends IndexShard implements Path<IndexShardRecord> {
        public <O extends Record> IndexShardPath(Table<O> path, ForeignKey<O, IndexShardRecord> childPath, InverseForeignKey<O, IndexShardRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private IndexShardPath(Name alias, Table<IndexShardRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public IndexShardPath as(String alias) {
            return new IndexShardPath(DSL.name(alias), this);
        }

        @Override
        public IndexShardPath as(Name alias) {
            return new IndexShardPath(alias, this);
        }

        @Override
        public IndexShardPath as(Table<?> alias) {
            return new IndexShardPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Stroom.STROOM;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.INDEX_SHARD_INDEX_SHARD_INDEX_UUID);
    }

    @Override
    public Identity<IndexShardRecord, Long> getIdentity() {
        return (Identity<IndexShardRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<IndexShardRecord> getPrimaryKey() {
        return Keys.KEY_INDEX_SHARD_PRIMARY;
    }

    @Override
    public List<ForeignKey<IndexShardRecord, ?>> getReferences() {
        return Arrays.asList(Keys.INDEX_SHARD_FK_VOLUME_ID);
    }

    private transient IndexVolumePath _indexVolume;

    /**
     * Get the implicit join path to the <code>stroom_v7_11.index_volume</code>
     * table.
     */
    public IndexVolumePath indexVolume() {
        if (_indexVolume == null)
            _indexVolume = new IndexVolumePath(this, Keys.INDEX_SHARD_FK_VOLUME_ID, null);

        return _indexVolume;
    }

    @Override
    public IndexShard as(String alias) {
        return new IndexShard(DSL.name(alias), this);
    }

    @Override
    public IndexShard as(Name alias) {
        return new IndexShard(alias, this);
    }

    @Override
    public IndexShard as(Table<?> alias) {
        return new IndexShard(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public IndexShard rename(String name) {
        return new IndexShard(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IndexShard rename(Name name) {
        return new IndexShard(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public IndexShard rename(Table<?> name) {
        return new IndexShard(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndexShard where(Condition condition) {
        return new IndexShard(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndexShard where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndexShard where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndexShard where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IndexShard where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IndexShard where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IndexShard where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IndexShard where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndexShard whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndexShard whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
