/*
 * This file is generated by jOOQ.
 */
package stroom.index.impl.db.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.JSON;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import stroom.index.impl.db.jooq.Keys;
import stroom.index.impl.db.jooq.Stroom;
import stroom.index.impl.db.jooq.tables.records.IndexFieldRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class IndexField extends TableImpl<IndexFieldRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>stroom.index_field</code>
     */
    public static final IndexField INDEX_FIELD = new IndexField();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IndexFieldRecord> getRecordType() {
        return IndexFieldRecord.class;
    }

    /**
     * The column <code>stroom.index_field.fk_index_field_source_id</code>.
     */
    public final TableField<IndexFieldRecord, Integer> FK_INDEX_FIELD_SOURCE_ID = createField(DSL.name("fk_index_field_source_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>stroom.index_field.type</code>.
     */
    public final TableField<IndexFieldRecord, Byte> TYPE = createField(DSL.name("type"), SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>stroom.index_field.name</code>.
     */
    public final TableField<IndexFieldRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(512).nullable(false), this, "");

    /**
     * The column <code>stroom.index_field.analyzer</code>.
     */
    public final TableField<IndexFieldRecord, String> ANALYZER = createField(DSL.name("analyzer"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stroom.index_field.indexed</code>.
     */
    public final TableField<IndexFieldRecord, Boolean> INDEXED = createField(DSL.name("indexed"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>stroom.index_field.stored</code>.
     */
    public final TableField<IndexFieldRecord, Boolean> STORED = createField(DSL.name("stored"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>stroom.index_field.term_positions</code>.
     */
    public final TableField<IndexFieldRecord, Boolean> TERM_POSITIONS = createField(DSL.name("term_positions"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>stroom.index_field.case_sensitive</code>.
     */
    public final TableField<IndexFieldRecord, Boolean> CASE_SENSITIVE = createField(DSL.name("case_sensitive"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>stroom.index_field.dense_vector</code>.
     */
    public final TableField<IndexFieldRecord, JSON> DENSE_VECTOR = createField(DSL.name("dense_vector"), SQLDataType.JSON, this, "");

    private IndexField(Name alias, Table<IndexFieldRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private IndexField(Name alias, Table<IndexFieldRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>stroom.index_field</code> table reference
     */
    public IndexField(String alias) {
        this(DSL.name(alias), INDEX_FIELD);
    }

    /**
     * Create an aliased <code>stroom.index_field</code> table reference
     */
    public IndexField(Name alias) {
        this(alias, INDEX_FIELD);
    }

    /**
     * Create a <code>stroom.index_field</code> table reference
     */
    public IndexField() {
        this(DSL.name("index_field"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Stroom.STROOM;
    }

    @Override
    public UniqueKey<IndexFieldRecord> getPrimaryKey() {
        return Keys.KEY_INDEX_FIELD_PRIMARY;
    }

    @Override
    public List<ForeignKey<IndexFieldRecord, ?>> getReferences() {
        return Arrays.asList(Keys.INDEX_FIELD_FK_INDEX_FIELD_SOURCE_ID);
    }

    @Override
    public IndexField as(String alias) {
        return new IndexField(DSL.name(alias), this);
    }

    @Override
    public IndexField as(Name alias) {
        return new IndexField(alias, this);
    }

    @Override
    public IndexField as(Table<?> alias) {
        return new IndexField(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public IndexField rename(String name) {
        return new IndexField(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IndexField rename(Name name) {
        return new IndexField(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public IndexField rename(Table<?> name) {
        return new IndexField(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndexField where(Condition condition) {
        return new IndexField(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndexField where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndexField where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndexField where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IndexField where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IndexField where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IndexField where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IndexField where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndexField whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndexField whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
