ALTER TABLE IDX_VOL ADD COLUMN IDX_UUID varchar(255) default NULL;
UPDATE IDX_VOL iv SET iv.IDX_UUID = (SELECT i.UUID FROM IDX i WHERE i.ID = iv.FK_IDX_ID);
ALTER TABLE IDX_VOL DROP FOREIGN KEY VOL_FK_IDX_ID;
ALTER TABLE IDX_VOL DROP PRIMARY KEY, ADD PRIMARY KEY(FK_VOL_ID, IDX_UUID);
ALTER TABLE IDX_VOL DROP COLUMN FK_IDX_ID;