/*
 * This file is generated by jOOQ.
 */
package stroom.data.store.impl.fs.db.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import stroom.data.store.impl.fs.db.jooq.tables.FsFeedPath;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FsFeedPathRecord extends UpdatableRecordImpl<FsFeedPathRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>stroom.fs_feed_path.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>stroom.fs_feed_path.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>stroom.fs_feed_path.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>stroom.fs_feed_path.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>stroom.fs_feed_path.path</code>.
     */
    public void setPath(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>stroom.fs_feed_path.path</code>.
     */
    public String getPath() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FsFeedPathRecord
     */
    public FsFeedPathRecord() {
        super(FsFeedPath.FS_FEED_PATH);
    }

    /**
     * Create a detached, initialised FsFeedPathRecord
     */
    public FsFeedPathRecord(Integer id, String name, String path) {
        super(FsFeedPath.FS_FEED_PATH);

        setId(id);
        setName(name);
        setPath(path);
        resetChangedOnNotNull();
    }
}
