ALTER TABLE IDX_SHRD ADD COLUMN IDX_UUID varchar(255) default NULL;
UPDATE IDX_SHRD shard SET shard.IDX_UUID = (SELECT ind.UUID FROM IDX ind WHERE ind.ID = shard.FK_IDX_ID);
ALTER TABLE IDX_SHRD DROP FOREIGN KEY IDX_SHRD_FK_IDX_ID;
ALTER TABLE IDX_SHRD CHANGE FK_IDX_ID OLD_IDX_ID int(11) default NULL;