/*
 * Copyright 2016 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

ALTER TABLE FOLDER          ADD COLUMN UUID varchar(255) DEFAULT NULL;
ALTER TABLE TXT_CONV        ADD COLUMN UUID varchar(255) DEFAULT NULL;
ALTER TABLE XSLT            ADD COLUMN UUID varchar(255) DEFAULT NULL;
ALTER TABLE XML_SCHEMA      ADD COLUMN UUID varchar(255) DEFAULT NULL;
ALTER TABLE PIPE            ADD COLUMN UUID varchar(255) DEFAULT NULL;
ALTER TABLE FD              ADD COLUMN UUID varchar(255) DEFAULT NULL;
ALTER TABLE IDX             ADD COLUMN UUID varchar(255) DEFAULT NULL;
ALTER TABLE STAT_DAT_SRC    ADD COLUMN UUID varchar(255) DEFAULT NULL;
ALTER TABLE DASH            ADD COLUMN UUID varchar(255) DEFAULT NULL;
ALTER TABLE SCRIPT          ADD COLUMN UUID varchar(255) DEFAULT NULL;
ALTER TABLE VIS             ADD COLUMN UUID varchar(255) DEFAULT NULL;
ALTER TABLE DICT            ADD COLUMN UUID varchar(255) DEFAULT NULL;
ALTER TABLE QUERY           ADD COLUMN UUID varchar(255) DEFAULT NULL;
ALTER TABLE SYS_USR         ADD COLUMN UUID varchar(255) DEFAULT NULL;
ALTER TABLE SYS_ROLE        ADD COLUMN UUID varchar(255) DEFAULT NULL;

ALTER TABLE FOLDER          ADD CONSTRAINT UNIQUE INDEX UUID (UUID);
ALTER TABLE TXT_CONV        ADD CONSTRAINT UNIQUE INDEX UUID (UUID);
ALTER TABLE XSLT            ADD CONSTRAINT UNIQUE INDEX UUID (UUID);
ALTER TABLE XML_SCHEMA      ADD CONSTRAINT UNIQUE INDEX UUID (UUID);
ALTER TABLE PIPE            ADD CONSTRAINT UNIQUE INDEX UUID (UUID);
ALTER TABLE FD              ADD CONSTRAINT UNIQUE INDEX UUID (UUID);
ALTER TABLE IDX             ADD CONSTRAINT UNIQUE INDEX UUID (UUID);
ALTER TABLE STAT_DAT_SRC    ADD CONSTRAINT UNIQUE INDEX UUID (UUID);
ALTER TABLE DASH            ADD CONSTRAINT UNIQUE INDEX UUID (UUID);
ALTER TABLE SCRIPT          ADD CONSTRAINT UNIQUE INDEX UUID (UUID);
ALTER TABLE VIS             ADD CONSTRAINT UNIQUE INDEX UUID (UUID);
ALTER TABLE DICT            ADD CONSTRAINT UNIQUE INDEX UUID (UUID);
ALTER TABLE QUERY           ADD CONSTRAINT UNIQUE INDEX UUID (UUID);
ALTER TABLE SYS_USR         ADD CONSTRAINT UNIQUE INDEX UUID (UUID);
ALTER TABLE SYS_ROLE        ADD CONSTRAINT UNIQUE INDEX UUID (UUID);

UPDATE FOLDER               SET UUID=uuid();
UPDATE TXT_CONV             SET UUID=uuid();
UPDATE XSLT                 SET UUID=uuid();
UPDATE XML_SCHEMA           SET UUID=uuid();
UPDATE PIPE                 SET UUID=uuid();
UPDATE FD                   SET UUID=uuid();
UPDATE IDX                  SET UUID=uuid();
UPDATE STAT_DAT_SRC         SET UUID=uuid();
UPDATE DASH                 SET UUID=uuid();
UPDATE SCRIPT               SET UUID=uuid();
UPDATE VIS                  SET UUID=uuid();
UPDATE DICT                 SET UUID=uuid();
UPDATE QUERY                SET UUID=uuid();
UPDATE SYS_USR              SET UUID=uuid();
UPDATE SYS_ROLE             SET UUID=uuid();

ALTER TABLE FOLDER          CHANGE COLUMN UUID UUID varchar(255) NOT NULL;
ALTER TABLE TXT_CONV        CHANGE COLUMN UUID UUID varchar(255) NOT NULL;
ALTER TABLE XSLT            CHANGE COLUMN UUID UUID varchar(255) NOT NULL;
ALTER TABLE XML_SCHEMA      CHANGE COLUMN UUID UUID varchar(255) NOT NULL;
ALTER TABLE PIPE            CHANGE COLUMN UUID UUID varchar(255) NOT NULL;
ALTER TABLE FD              CHANGE COLUMN UUID UUID varchar(255) NOT NULL;
ALTER TABLE IDX             CHANGE COLUMN UUID UUID varchar(255) NOT NULL;
ALTER TABLE STAT_DAT_SRC    CHANGE COLUMN UUID UUID varchar(255) NOT NULL;
ALTER TABLE DASH            CHANGE COLUMN UUID UUID varchar(255) NOT NULL;
ALTER TABLE SCRIPT          CHANGE COLUMN UUID UUID varchar(255) NOT NULL;
ALTER TABLE VIS             CHANGE COLUMN UUID UUID varchar(255) NOT NULL;
ALTER TABLE DICT            CHANGE COLUMN UUID UUID varchar(255) NOT NULL;
ALTER TABLE QUERY           CHANGE COLUMN UUID UUID varchar(255) NOT NULL;
ALTER TABLE SYS_USR         CHANGE COLUMN UUID UUID varchar(255) NOT NULL;
ALTER TABLE SYS_ROLE        CHANGE COLUMN UUID UUID varchar(255) NOT NULL;
