ALTER TABLE QUERY DROP FOREIGN KEY QUERY_FK_DASH_ID;
ALTER TABLE QUERY DROP INDEX QUERY_FK_DASH_ID;
ALTER TABLE QUERY CHANGE COLUMN FK_DASH_ID DASH_ID bigint(20) default NULL;
ALTER TABLE QUERY ADD COLUMN QUERY_ID varchar(255) default NULL;