SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE OLD_FD LIKE FD;
INSERT OLD_FD SELECT * FROM FD;

ALTER TABLE FD DROP FOREIGN KEY FD_FK_STRM_TP_ID;

ALTER TABLE FD DROP COLUMN VER;
ALTER TABLE FD DROP COLUMN CRT_USER;
ALTER TABLE FD DROP COLUMN UPD_USER;
ALTER TABLE FD DROP COLUMN CRT_MS;
ALTER TABLE FD DROP COLUMN UPD_MS;
ALTER TABLE FD DROP COLUMN UUID;
ALTER TABLE FD DROP COLUMN DESCRIP;
ALTER TABLE FD DROP COLUMN FK_STRM_TP_ID;
ALTER TABLE FD DROP COLUMN CLS;
ALTER TABLE FD DROP COLUMN ENC;
ALTER TABLE FD DROP COLUMN CTX_ENC;
ALTER TABLE FD DROP COLUMN STAT;
ALTER TABLE FD DROP COLUMN RETEN_DAY_AGE;
ALTER TABLE FD DROP COLUMN REF;

RENAME TABLE FD TO stream_feed;
ALTER TABLE stream_feed CHANGE ID id int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE stream_feed CHANGE NAME name varchar(255) NOT NULL;

CREATE TABLE file_feed_path (
  id 				int(11) NOT NULL AUTO_INCREMENT,
  name 		        varchar(255) NOT NULL,
  path 		        varchar(255) NOT NULL,
  PRIMARY KEY       (id),
  UNIQUE KEY		name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO file_feed_path (id, name, path) SELECT o.ID, o.NAME, o.ID FROM OLD_FD o;

SET FOREIGN_KEY_CHECKS=1;