SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE PROCESSOR LIKE STRM_PROC;
INSERT PROCESSOR SELECT * FROM STRM_PROC;

ALTER TABLE STRM_PROC DROP COLUMN VER;
ALTER TABLE STRM_PROC DROP COLUMN CRT_USER;
ALTER TABLE STRM_PROC DROP COLUMN UPD_USER;
ALTER TABLE STRM_PROC DROP COLUMN TASK_TP;
ALTER TABLE STRM_PROC DROP COLUMN ENBL;
ALTER TABLE STRM_PROC DROP COLUMN CRT_MS;
ALTER TABLE STRM_PROC DROP COLUMN UPD_MS;
ALTER TABLE STRM_PROC ADD COLUMN PROCESSOR_ID int(11) NOT NULL;
UPDATE STRM_PROC SET PROCESSOR_ID = ID;
RENAME TABLE STRM_PROC TO stream_processor;
ALTER TABLE stream_processor CHANGE ID id int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE stream_processor CHANGE PIPE_UUID pipeline_uuid varchar(255) NOT NULL;
ALTER TABLE stream_processor CHANGE PROCESSOR_ID processor_id int(11) NOT NULL;

RENAME TABLE STRM_PROC_FILT_TRAC TO PROCESSOR_FILTER_TRACKER;
ALTER TABLE STRM_PROC_FILT DROP FOREIGN KEY STRM_PROC_FILT_FK_STRM_PROC_FILT_TRAC_ID;
ALTER TABLE STRM_PROC_FILT DROP FOREIGN KEY STRM_PROC_FILT_FK_STRM_PROC_ID;
RENAME TABLE STRM_PROC_FILT TO PROCESSOR_FILTER;
ALTER TABLE PROCESSOR_FILTER CHANGE FK_STRM_PROC_ID FK_PROCESSOR_ID int(11) NOT NULL;
ALTER TABLE PROCESSOR_FILTER CHANGE FK_STRM_PROC_FILT_TRAC_ID FK_PROCESSOR_FILTER_TRACKER_ID int(11) NOT NULL;
ALTER TABLE PROCESSOR_FILTER ADD CONSTRAINT PROCESSOR_FILTER_FK_PROCESSOR_ID FOREIGN KEY (FK_PROCESSOR_ID) REFERENCES PROCESSOR(ID);
ALTER TABLE PROCESSOR_FILTER ADD CONSTRAINT PROCESSOR_FILTER_FK_PROCESSOR_FILTER_TRACKER_ID FOREIGN KEY (FK_PROCESSOR_FILTER_TRACKER_ID) REFERENCES PROCESSOR_FILTER_TRACKER(ID);

ALTER TABLE STRM_TASK DROP FOREIGN KEY STRM_TASK_FK_STRM_PROC_FILT_ID;
ALTER TABLE STRM_TASK DROP FOREIGN KEY STRM_TASK_FK_ND_ID;
RENAME TABLE STRM_TASK TO PROCESSOR_FILTER_TASK;
ALTER TABLE PROCESSOR_FILTER_TASK CHANGE FK_STRM_PROC_FILT_ID FK_PROCESSOR_FILTER_ID int(11) NOT NULL;
ALTER TABLE PROCESSOR_FILTER_TASK ADD CONSTRAINT PROCESSOR_FILTER_TASK_FK_PROCESSOR_FILTER_ID FOREIGN KEY (FK_PROCESSOR_FILTER_ID) REFERENCES PROCESSOR_FILTER(ID);
ALTER TABLE PROCESSOR_FILTER_TASK ADD CONSTRAINT PROCESSOR_FILTER_TASK_FK_ND_ID FOREIGN KEY (FK_ND_ID) REFERENCES ND(ID);

SET FOREIGN_KEY_CHECKS=1;