SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE OLD_FD LIKE FD;
INSERT OLD_FD SELECT * FROM FD;

ALTER TABLE FD DROP FOREIGN KEY FD_FK_STRM_TP_ID;

ALTER TABLE FD DROP COLUMN VER;
ALTER TABLE FD DROP COLUMN CRT_USER;
ALTER TABLE FD DROP COLUMN UPD_USER;
ALTER TABLE FD DROP COLUMN CRT_MS;
ALTER TABLE FD DROP COLUMN UPD_MS;
ALTER TABLE FD DROP COLUMN UUID;
ALTER TABLE FD DROP COLUMN DESCRIP;
ALTER TABLE FD DROP COLUMN FK_STRM_TP_ID;
ALTER TABLE FD DROP COLUMN CLS;
ALTER TABLE FD DROP COLUMN ENC;
ALTER TABLE FD DROP COLUMN CTX_ENC;
ALTER TABLE FD DROP COLUMN STAT;
ALTER TABLE FD DROP COLUMN RETEN_DAY_AGE;
ALTER TABLE FD DROP COLUMN REF;

RENAME TABLE FD TO STRM_FEED;

CREATE TABLE FS_FEED_PATH (
  ID 				int(11) NOT NULL AUTO_INCREMENT,
  NAME 		        varchar(255) NOT NULL,
  PATH 		        varchar(255) NOT NULL,
  PRIMARY KEY       (ID),
  UNIQUE KEY		NAME (NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO FS_FEED_PATH (FS_FEED_PATH.ID, FS_FEED_PATH.NAME, FS_FEED_PATH.PATH) SELECT OLD_FD.ID, OLD_FD.NAME, OLD_FD.ID FROM OLD_FD;

SET FOREIGN_KEY_CHECKS=1;