SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE OLD_STRM_TP LIKE STRM_TP;
INSERT OLD_STRM_TP SELECT * FROM STRM_TP;

ALTER TABLE STRM_TP DROP COLUMN VER;
ALTER TABLE STRM_TP DROP COLUMN CRT_USER;
ALTER TABLE STRM_TP DROP COLUMN UPD_USER;
ALTER TABLE STRM_TP DROP COLUMN CRT_MS;
ALTER TABLE STRM_TP DROP COLUMN UPD_MS;
ALTER TABLE STRM_TP DROP COLUMN EXT;
ALTER TABLE STRM_TP DROP COLUMN PURP;
ALTER TABLE STRM_TP DROP COLUMN PATH;

RENAME TABLE STRM_TP TO STRM_TYPE;

CREATE TABLE FS_TYPE_PATH (
  ID 				int(11) NOT NULL AUTO_INCREMENT,
  NAME 		        varchar(255) NOT NULL,
  PATH 		        varchar(255) NOT NULL,
  PRIMARY KEY       (ID),
  UNIQUE KEY		NAME (NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO FS_TYPE_PATH (FS_TYPE_PATH.ID, FS_TYPE_PATH.NAME, FS_TYPE_PATH.PATH) SELECT OLD_STRM_TP.ID, OLD_STRM_TP.NAME, OLD_STRM_TP.PATH FROM OLD_STRM_TP WHERE CHAR_LENGTH(OLD_STRM_TP.PATH) > 1;

SET FOREIGN_KEY_CHECKS=1;