SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE OLD_STRM_TP LIKE STRM_TP;
INSERT OLD_STRM_TP SELECT * FROM STRM_TP;

ALTER TABLE STRM_TP DROP COLUMN VER;
ALTER TABLE STRM_TP DROP COLUMN CRT_USER;
ALTER TABLE STRM_TP DROP COLUMN UPD_USER;
ALTER TABLE STRM_TP DROP COLUMN CRT_MS;
ALTER TABLE STRM_TP DROP COLUMN UPD_MS;
ALTER TABLE STRM_TP DROP COLUMN EXT;
ALTER TABLE STRM_TP DROP COLUMN PURP;
ALTER TABLE STRM_TP DROP COLUMN PATH;

RENAME TABLE STRM_TP TO data_type;
ALTER TABLE data_type CHANGE ID id int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE data_type CHANGE NAME name varchar(255) NOT NULL;

CREATE TABLE file_type_path (
  id 				int(11) NOT NULL AUTO_INCREMENT,
  name 		        varchar(255) NOT NULL,
  path 		        varchar(255) NOT NULL,
  PRIMARY KEY       (id),
  UNIQUE KEY		name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO file_type_path (id, name, path) SELECT o.ID, o.NAME, o.PATH FROM OLD_STRM_TP o WHERE CHAR_LENGTH(o.PATH) > 1;

SET FOREIGN_KEY_CHECKS=1;