/*
 * This file is generated by jOOQ.
 */
package stroom.processor.impl.db.jooq.tables;


import stroom.processor.impl.db.jooq.Indexes;
import stroom.processor.impl.db.jooq.Keys;
import stroom.processor.impl.db.jooq.Stroom;
import stroom.processor.impl.db.jooq.tables.ProcessorFeed.ProcessorFeedPath;
import stroom.processor.impl.db.jooq.tables.ProcessorFilter.ProcessorFilterPath;
import stroom.processor.impl.db.jooq.tables.ProcessorNode.ProcessorNodePath;
import stroom.processor.impl.db.jooq.tables.records.ProcessorTaskRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProcessorTask extends TableImpl<ProcessorTaskRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>stroom.processor_task</code>
     */
    public static final ProcessorTask PROCESSOR_TASK = new ProcessorTask();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProcessorTaskRecord> getRecordType() {
        return ProcessorTaskRecord.class;
    }

    /**
     * The column <code>stroom.processor_task.id</code>.
     */
    public final TableField<ProcessorTaskRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>stroom.processor_task.version</code>.
     */
    public final TableField<ProcessorTaskRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>stroom.processor_task.fk_processor_filter_id</code>.
     */
    public final TableField<ProcessorTaskRecord, Integer> FK_PROCESSOR_FILTER_ID = createField(DSL.name("fk_processor_filter_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>stroom.processor_task.fk_processor_node_id</code>.
     */
    public final TableField<ProcessorTaskRecord, Integer> FK_PROCESSOR_NODE_ID = createField(DSL.name("fk_processor_node_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>stroom.processor_task.fk_processor_feed_id</code>.
     */
    public final TableField<ProcessorTaskRecord, Integer> FK_PROCESSOR_FEED_ID = createField(DSL.name("fk_processor_feed_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>stroom.processor_task.create_time_ms</code>.
     */
    public final TableField<ProcessorTaskRecord, Long> CREATE_TIME_MS = createField(DSL.name("create_time_ms"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stroom.processor_task.start_time_ms</code>.
     */
    public final TableField<ProcessorTaskRecord, Long> START_TIME_MS = createField(DSL.name("start_time_ms"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stroom.processor_task.end_time_ms</code>.
     */
    public final TableField<ProcessorTaskRecord, Long> END_TIME_MS = createField(DSL.name("end_time_ms"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stroom.processor_task.status</code>.
     */
    public final TableField<ProcessorTaskRecord, Byte> STATUS = createField(DSL.name("status"), SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>stroom.processor_task.status_time_ms</code>.
     */
    public final TableField<ProcessorTaskRecord, Long> STATUS_TIME_MS = createField(DSL.name("status_time_ms"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stroom.processor_task.meta_id</code>.
     */
    public final TableField<ProcessorTaskRecord, Long> META_ID = createField(DSL.name("meta_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>stroom.processor_task.data</code>.
     */
    public final TableField<ProcessorTaskRecord, String> DATA = createField(DSL.name("data"), SQLDataType.CLOB, this, "");

    private ProcessorTask(Name alias, Table<ProcessorTaskRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ProcessorTask(Name alias, Table<ProcessorTaskRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>stroom.processor_task</code> table reference
     */
    public ProcessorTask(String alias) {
        this(DSL.name(alias), PROCESSOR_TASK);
    }

    /**
     * Create an aliased <code>stroom.processor_task</code> table reference
     */
    public ProcessorTask(Name alias) {
        this(alias, PROCESSOR_TASK);
    }

    /**
     * Create a <code>stroom.processor_task</code> table reference
     */
    public ProcessorTask() {
        this(DSL.name("processor_task"), null);
    }

    public <O extends Record> ProcessorTask(Table<O> path, ForeignKey<O, ProcessorTaskRecord> childPath, InverseForeignKey<O, ProcessorTaskRecord> parentPath) {
        super(path, childPath, parentPath, PROCESSOR_TASK);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ProcessorTaskPath extends ProcessorTask implements Path<ProcessorTaskRecord> {
        public <O extends Record> ProcessorTaskPath(Table<O> path, ForeignKey<O, ProcessorTaskRecord> childPath, InverseForeignKey<O, ProcessorTaskRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ProcessorTaskPath(Name alias, Table<ProcessorTaskRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ProcessorTaskPath as(String alias) {
            return new ProcessorTaskPath(DSL.name(alias), this);
        }

        @Override
        public ProcessorTaskPath as(Name alias) {
            return new ProcessorTaskPath(alias, this);
        }

        @Override
        public ProcessorTaskPath as(Table<?> alias) {
            return new ProcessorTaskPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Stroom.STROOM;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.PROCESSOR_TASK_PROCESSOR_TASK_FILTER_ID_STATUS_ID_META_ID, Indexes.PROCESSOR_TASK_PROCESSOR_TASK_META_ID_IDX, Indexes.PROCESSOR_TASK_PROCESSOR_TASK_STATUS_CREATE_TIME_MS_IDX, Indexes.PROCESSOR_TASK_PROCESSOR_TASK_STATUS_TIME_MS_STATUS_IDX);
    }

    @Override
    public Identity<ProcessorTaskRecord, Long> getIdentity() {
        return (Identity<ProcessorTaskRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ProcessorTaskRecord> getPrimaryKey() {
        return Keys.KEY_PROCESSOR_TASK_PRIMARY;
    }

    @Override
    public List<ForeignKey<ProcessorTaskRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PROCESSOR_TASK_FK_PROCESSOR_FILTER_ID, Keys.PROCESSOR_TASK_FK_PROCESSOR_NODE_ID, Keys.PROCESSOR_TASK_FK_PROCESSOR_FEED_ID);
    }

    private transient ProcessorFilterPath _processorFilter;

    /**
     * Get the implicit join path to the <code>stroom.processor_filter</code>
     * table.
     */
    public ProcessorFilterPath processorFilter() {
        if (_processorFilter == null)
            _processorFilter = new ProcessorFilterPath(this, Keys.PROCESSOR_TASK_FK_PROCESSOR_FILTER_ID, null);

        return _processorFilter;
    }

    private transient ProcessorNodePath _processorNode;

    /**
     * Get the implicit join path to the <code>stroom.processor_node</code>
     * table.
     */
    public ProcessorNodePath processorNode() {
        if (_processorNode == null)
            _processorNode = new ProcessorNodePath(this, Keys.PROCESSOR_TASK_FK_PROCESSOR_NODE_ID, null);

        return _processorNode;
    }

    private transient ProcessorFeedPath _processorFeed;

    /**
     * Get the implicit join path to the <code>stroom.processor_feed</code>
     * table.
     */
    public ProcessorFeedPath processorFeed() {
        if (_processorFeed == null)
            _processorFeed = new ProcessorFeedPath(this, Keys.PROCESSOR_TASK_FK_PROCESSOR_FEED_ID, null);

        return _processorFeed;
    }

    @Override
    public TableField<ProcessorTaskRecord, Integer> getRecordVersion() {
        return VERSION;
    }

    @Override
    public ProcessorTask as(String alias) {
        return new ProcessorTask(DSL.name(alias), this);
    }

    @Override
    public ProcessorTask as(Name alias) {
        return new ProcessorTask(alias, this);
    }

    @Override
    public ProcessorTask as(Table<?> alias) {
        return new ProcessorTask(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcessorTask rename(String name) {
        return new ProcessorTask(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcessorTask rename(Name name) {
        return new ProcessorTask(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcessorTask rename(Table<?> name) {
        return new ProcessorTask(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcessorTask where(Condition condition) {
        return new ProcessorTask(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcessorTask where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcessorTask where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcessorTask where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProcessorTask where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProcessorTask where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProcessorTask where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProcessorTask where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcessorTask whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcessorTask whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
