/*
 * This file is generated by jOOQ.
 */
package stroom.analytics.impl.db.jooq.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row12;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import stroom.analytics.impl.db.jooq.Indexes;
import stroom.analytics.impl.db.jooq.Keys;
import stroom.analytics.impl.db.jooq.Stroom;
import stroom.analytics.impl.db.jooq.tables.records.AnalyticProcessorFilterRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AnalyticProcessorFilter extends TableImpl<AnalyticProcessorFilterRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>stroom.analytic_processor_filter</code>
     */
    public static final AnalyticProcessorFilter ANALYTIC_PROCESSOR_FILTER = new AnalyticProcessorFilter();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AnalyticProcessorFilterRecord> getRecordType() {
        return AnalyticProcessorFilterRecord.class;
    }

    /**
     * The column <code>stroom.analytic_processor_filter.uuid</code>.
     */
    public final TableField<AnalyticProcessorFilterRecord, String> UUID = createField(DSL.name("uuid"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stroom.analytic_processor_filter.version</code>.
     */
    public final TableField<AnalyticProcessorFilterRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>stroom.analytic_processor_filter.create_time_ms</code>.
     */
    public final TableField<AnalyticProcessorFilterRecord, Long> CREATE_TIME_MS = createField(DSL.name("create_time_ms"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>stroom.analytic_processor_filter.create_user</code>.
     */
    public final TableField<AnalyticProcessorFilterRecord, String> CREATE_USER = createField(DSL.name("create_user"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stroom.analytic_processor_filter.update_time_ms</code>.
     */
    public final TableField<AnalyticProcessorFilterRecord, Long> UPDATE_TIME_MS = createField(DSL.name("update_time_ms"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>stroom.analytic_processor_filter.update_user</code>.
     */
    public final TableField<AnalyticProcessorFilterRecord, String> UPDATE_USER = createField(DSL.name("update_user"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stroom.analytic_processor_filter.analytic_uuid</code>.
     */
    public final TableField<AnalyticProcessorFilterRecord, String> ANALYTIC_UUID = createField(DSL.name("analytic_uuid"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stroom.analytic_processor_filter.expression</code>.
     */
    public final TableField<AnalyticProcessorFilterRecord, String> EXPRESSION = createField(DSL.name("expression"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>stroom.analytic_processor_filter.min_meta_create_time_ms</code>.
     */
    public final TableField<AnalyticProcessorFilterRecord, Long> MIN_META_CREATE_TIME_MS = createField(DSL.name("min_meta_create_time_ms"), SQLDataType.BIGINT, this, "");

    /**
     * The column
     * <code>stroom.analytic_processor_filter.max_meta_create_time_ms</code>.
     */
    public final TableField<AnalyticProcessorFilterRecord, Long> MAX_META_CREATE_TIME_MS = createField(DSL.name("max_meta_create_time_ms"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stroom.analytic_processor_filter.node</code>.
     */
    public final TableField<AnalyticProcessorFilterRecord, String> NODE = createField(DSL.name("node"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stroom.analytic_processor_filter.enabled</code>.
     */
    public final TableField<AnalyticProcessorFilterRecord, Boolean> ENABLED = createField(DSL.name("enabled"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BOOLEAN)), this, "");

    private AnalyticProcessorFilter(Name alias, Table<AnalyticProcessorFilterRecord> aliased) {
        this(alias, aliased, null);
    }

    private AnalyticProcessorFilter(Name alias, Table<AnalyticProcessorFilterRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>stroom.analytic_processor_filter</code> table
     * reference
     */
    public AnalyticProcessorFilter(String alias) {
        this(DSL.name(alias), ANALYTIC_PROCESSOR_FILTER);
    }

    /**
     * Create an aliased <code>stroom.analytic_processor_filter</code> table
     * reference
     */
    public AnalyticProcessorFilter(Name alias) {
        this(alias, ANALYTIC_PROCESSOR_FILTER);
    }

    /**
     * Create a <code>stroom.analytic_processor_filter</code> table reference
     */
    public AnalyticProcessorFilter() {
        this(DSL.name("analytic_processor_filter"), null);
    }

    public <O extends Record> AnalyticProcessorFilter(Table<O> child, ForeignKey<O, AnalyticProcessorFilterRecord> key) {
        super(child, key, ANALYTIC_PROCESSOR_FILTER);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Stroom.STROOM;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ANALYTIC_PROCESSOR_FILTER_ANALYTIC_PROCESSOR_FILTER_ANALYTIC_UUID_IDX);
    }

    @Override
    public UniqueKey<AnalyticProcessorFilterRecord> getPrimaryKey() {
        return Keys.KEY_ANALYTIC_PROCESSOR_FILTER_PRIMARY;
    }

    @Override
    public TableField<AnalyticProcessorFilterRecord, Integer> getRecordVersion() {
        return VERSION;
    }

    @Override
    public AnalyticProcessorFilter as(String alias) {
        return new AnalyticProcessorFilter(DSL.name(alias), this);
    }

    @Override
    public AnalyticProcessorFilter as(Name alias) {
        return new AnalyticProcessorFilter(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AnalyticProcessorFilter rename(String name) {
        return new AnalyticProcessorFilter(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AnalyticProcessorFilter rename(Name name) {
        return new AnalyticProcessorFilter(name, null);
    }

    // -------------------------------------------------------------------------
    // Row12 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row12<String, Integer, Long, String, Long, String, String, String, Long, Long, String, Boolean> fieldsRow() {
        return (Row12) super.fieldsRow();
    }
}
