/*
 * This file is generated by jOOQ.
 */
package stroom.data.store.impl.fs.db.jooq;


import stroom.data.store.impl.fs.db.jooq.tables.FsFeedPath;
import stroom.data.store.impl.fs.db.jooq.tables.FsMetaVolume;
import stroom.data.store.impl.fs.db.jooq.tables.FsOrphanedMetaTracker;
import stroom.data.store.impl.fs.db.jooq.tables.FsTypePath;
import stroom.data.store.impl.fs.db.jooq.tables.FsVolume;
import stroom.data.store.impl.fs.db.jooq.tables.FsVolumeGroup;
import stroom.data.store.impl.fs.db.jooq.tables.FsVolumeState;
import stroom.data.store.impl.fs.db.jooq.tables.ZstdDictionary;
import stroom.data.store.impl.fs.db.jooq.tables.ZstdDictionaryTask;


/**
 * Convenience access to all tables in stroom.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>stroom.fs_feed_path</code>.
     */
    public static final FsFeedPath FS_FEED_PATH = FsFeedPath.FS_FEED_PATH;

    /**
     * The table <code>stroom.fs_meta_volume</code>.
     */
    public static final FsMetaVolume FS_META_VOLUME = FsMetaVolume.FS_META_VOLUME;

    /**
     * The table <code>stroom.fs_orphaned_meta_tracker</code>.
     */
    public static final FsOrphanedMetaTracker FS_ORPHANED_META_TRACKER = FsOrphanedMetaTracker.FS_ORPHANED_META_TRACKER;

    /**
     * The table <code>stroom.fs_type_path</code>.
     */
    public static final FsTypePath FS_TYPE_PATH = FsTypePath.FS_TYPE_PATH;

    /**
     * The table <code>stroom.fs_volume</code>.
     */
    public static final FsVolume FS_VOLUME = FsVolume.FS_VOLUME;

    /**
     * The table <code>stroom.fs_volume_group</code>.
     */
    public static final FsVolumeGroup FS_VOLUME_GROUP = FsVolumeGroup.FS_VOLUME_GROUP;

    /**
     * The table <code>stroom.fs_volume_state</code>.
     */
    public static final FsVolumeState FS_VOLUME_STATE = FsVolumeState.FS_VOLUME_STATE;

    /**
     * The table <code>stroom.zstd_dictionary</code>.
     */
    public static final ZstdDictionary ZSTD_DICTIONARY = ZstdDictionary.ZSTD_DICTIONARY;

    /**
     * The table <code>stroom.zstd_dictionary_task</code>.
     */
    public static final ZstdDictionaryTask ZSTD_DICTIONARY_TASK = ZstdDictionaryTask.ZSTD_DICTIONARY_TASK;
}
