/*
 * Copyright 2016 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

ALTER TABLE SYS_GRP         DROP FOREIGN KEY SYS_GRP_FK_SYS_GRP_ID;
ALTER TABLE SYS_USR_GRP     DROP FOREIGN KEY SYS_USR_GRP_FK_SYS_GRP_ID;
ALTER TABLE DICT            DROP FOREIGN KEY DICT_FK_SYS_GRP_ID;
ALTER TABLE FD              DROP FOREIGN KEY FD_FK_SYS_GRP_ID;
ALTER TABLE IDX             DROP FOREIGN KEY IDX_FK_SYS_GRP_ID;
ALTER TABLE PIPE            DROP FOREIGN KEY PIPE_FK_SYS_GRP_ID;
ALTER TABLE TXT_CONV        DROP FOREIGN KEY TXT_CONV_FK_SYS_GRP_ID;
ALTER TABLE XML_SCHEMA      DROP FOREIGN KEY XML_SCHEMA_FK_SYS_GRP_ID;
ALTER TABLE XSLT            DROP FOREIGN KEY XSLT_FK_SYS_GRP_ID;
ALTER TABLE DASH            DROP FOREIGN KEY DASH_FK_SYS_GRP_ID;
ALTER TABLE SCRIPT          DROP FOREIGN KEY SCRIPT_FK_SYS_GRP_ID;
ALTER TABLE VIS             DROP FOREIGN KEY VIS_FK_SYS_GRP_ID;
ALTER TABLE STAT_DAT_SRC    DROP FOREIGN KEY STAT_DAT_SRC_FK_SYS_GRP_ID;

--ALTER TABLE SYS_GRP         DROP INDEX SYS_GRP_FK_SYS_GRP_ID;
--ALTER TABLE SYS_USR_GRP     DROP INDEX SYS_USR_GRP_FK_SYS_GRP_ID;
--ALTER TABLE DICT            DROP INDEX DICT_FK_SYS_GRP_ID;
--ALTER TABLE FD              DROP INDEX FD_FK_SYS_GRP_ID;
--ALTER TABLE IDX             DROP INDEX IDX_FK_SYS_GRP_ID;
--ALTER TABLE PIPE            DROP INDEX PIPE_FK_SYS_GRP_ID;
--ALTER TABLE TXT_CONV        DROP INDEX TXT_CONV_FK_SYS_GRP_ID;
--ALTER TABLE XML_SCHEMA      DROP INDEX XML_SCHEMA_FK_SYS_GRP_ID;
--ALTER TABLE XSLT            DROP INDEX XSLT_FK_SYS_GRP_ID;
--ALTER TABLE DASH            DROP INDEX DASH_FK_SYS_GRP_ID;
--ALTER TABLE SCRIPT          DROP INDEX SCRIPT_FK_SYS_GRP_ID;
--ALTER TABLE VIS             DROP INDEX VIS_FK_SYS_GRP_ID;
--ALTER TABLE STAT_DAT_SRC    DROP INDEX STAT_DAT_SRC_FK_SYS_GRP_ID;

ALTER TABLE SYS_GRP         DROP INDEX FK_SYS_GRP_ID;
ALTER TABLE DICT            DROP INDEX FK_SYS_GRP_ID;
ALTER TABLE IDX             DROP INDEX FK_SYS_GRP_ID;
ALTER TABLE PIPE            DROP INDEX FK_SYS_GRP_ID;
ALTER TABLE TXT_CONV        DROP INDEX FK_SYS_GRP_ID;
ALTER TABLE XML_SCHEMA      DROP INDEX FK_SYS_GRP_ID;
ALTER TABLE XSLT            DROP INDEX FK_SYS_GRP_ID;
ALTER TABLE DASH            DROP INDEX FK_SYS_GRP_ID;
ALTER TABLE SCRIPT          DROP INDEX FK_SYS_GRP_ID;
ALTER TABLE VIS             DROP INDEX FK_SYS_GRP_ID;
ALTER TABLE STAT_DAT_SRC    DROP INDEX NAME;

RENAME TABLE SYS_GRP TO FOLDER;

ALTER TABLE FOLDER          CHANGE COLUMN FK_SYS_GRP_ID FK_FOLDER_ID int(11) default NULL;
ALTER TABLE SYS_USR_GRP     CHANGE COLUMN FK_SYS_GRP_ID FK_FOLDER_ID int(11) NOT NULL;
ALTER TABLE DICT            CHANGE COLUMN FK_SYS_GRP_ID FK_FOLDER_ID int(11) default NULL;
ALTER TABLE FD              CHANGE COLUMN FK_SYS_GRP_ID FK_FOLDER_ID int(11) default NULL;
ALTER TABLE IDX             CHANGE COLUMN FK_SYS_GRP_ID FK_FOLDER_ID int(11) default NULL;
ALTER TABLE PIPE            CHANGE COLUMN FK_SYS_GRP_ID FK_FOLDER_ID int(11) default NULL;
ALTER TABLE TXT_CONV        CHANGE COLUMN FK_SYS_GRP_ID FK_FOLDER_ID int(11) default NULL;
ALTER TABLE XML_SCHEMA      CHANGE COLUMN FK_SYS_GRP_ID FK_FOLDER_ID int(11) default NULL;
ALTER TABLE XSLT            CHANGE COLUMN FK_SYS_GRP_ID FK_FOLDER_ID int(11) default NULL;
ALTER TABLE DASH            CHANGE COLUMN FK_SYS_GRP_ID FK_FOLDER_ID int(11) default NULL;
ALTER TABLE SCRIPT          CHANGE COLUMN FK_SYS_GRP_ID FK_FOLDER_ID int(11) default NULL;
ALTER TABLE VIS             CHANGE COLUMN FK_SYS_GRP_ID FK_FOLDER_ID int(11) default NULL;
ALTER TABLE STAT_DAT_SRC    CHANGE COLUMN FK_SYS_GRP_ID FK_FOLDER_ID int(11) default NULL;

ALTER TABLE FOLDER          ADD CONSTRAINT FK_FOLDER_ID                 FOREIGN KEY (FK_FOLDER_ID) REFERENCES FOLDER(ID);
ALTER TABLE SYS_USR_GRP     ADD CONSTRAINT SYS_USR_GRP_FK_FOLDER_ID     FOREIGN KEY (FK_FOLDER_ID) REFERENCES FOLDER(ID);
ALTER TABLE DICT            ADD CONSTRAINT DICT_FK_FOLDER_ID            FOREIGN KEY (FK_FOLDER_ID) REFERENCES FOLDER(ID);
ALTER TABLE FD              ADD CONSTRAINT FD_FK_FOLDER_ID              FOREIGN KEY (FK_FOLDER_ID) REFERENCES FOLDER(ID);
ALTER TABLE IDX             ADD CONSTRAINT IDX_FK_FOLDER_ID             FOREIGN KEY (FK_FOLDER_ID) REFERENCES FOLDER(ID);
ALTER TABLE PIPE            ADD CONSTRAINT PIPE_FK_FOLDER_ID            FOREIGN KEY (FK_FOLDER_ID) REFERENCES FOLDER(ID);
ALTER TABLE TXT_CONV        ADD CONSTRAINT TXT_CONV_FK_FOLDER_ID        FOREIGN KEY (FK_FOLDER_ID) REFERENCES FOLDER(ID);
ALTER TABLE XML_SCHEMA      ADD CONSTRAINT XML_SCHEMA_FK_FOLDER_ID      FOREIGN KEY (FK_FOLDER_ID) REFERENCES FOLDER(ID);
ALTER TABLE XSLT            ADD CONSTRAINT XSLT_FK_FOLDER_ID            FOREIGN KEY (FK_FOLDER_ID) REFERENCES FOLDER(ID);
ALTER TABLE DASH            ADD CONSTRAINT DASH_FK_FOLDER_ID            FOREIGN KEY (FK_FOLDER_ID) REFERENCES FOLDER(ID);
ALTER TABLE SCRIPT          ADD CONSTRAINT SCRIPT_FK_FOLDER_ID          FOREIGN KEY (FK_FOLDER_ID) REFERENCES FOLDER(ID);
ALTER TABLE VIS             ADD CONSTRAINT VIS_FK_FOLDER_ID             FOREIGN KEY (FK_FOLDER_ID) REFERENCES FOLDER(ID);
ALTER TABLE STAT_DAT_SRC    ADD CONSTRAINT STAT_DAT_SRC_FK_FOLDER_ID    FOREIGN KEY (FK_FOLDER_ID) REFERENCES FOLDER(ID);

ALTER TABLE FOLDER          ADD CONSTRAINT UNIQUE INDEX NAME (FK_FOLDER_ID,NAME);
ALTER TABLE DICT            ADD CONSTRAINT UNIQUE INDEX NAME (FK_FOLDER_ID,NAME);
ALTER TABLE IDX             ADD CONSTRAINT UNIQUE INDEX NAME (FK_FOLDER_ID,NAME);
ALTER TABLE PIPE            ADD CONSTRAINT UNIQUE INDEX NAME (FK_FOLDER_ID,NAME);
ALTER TABLE TXT_CONV        ADD CONSTRAINT UNIQUE INDEX NAME (FK_FOLDER_ID,NAME);
ALTER TABLE XML_SCHEMA      ADD CONSTRAINT UNIQUE INDEX NAME (FK_FOLDER_ID,NAME);
ALTER TABLE XSLT            ADD CONSTRAINT UNIQUE INDEX NAME (FK_FOLDER_ID,NAME);
ALTER TABLE DASH            ADD CONSTRAINT UNIQUE INDEX NAME (FK_FOLDER_ID,NAME);
ALTER TABLE SCRIPT          ADD CONSTRAINT UNIQUE INDEX NAME (FK_FOLDER_ID,NAME);
ALTER TABLE VIS             ADD CONSTRAINT UNIQUE INDEX NAME (FK_FOLDER_ID,NAME);
ALTER TABLE STAT_DAT_SRC    ADD CONSTRAINT UNIQUE INDEX NAME (FK_FOLDER_ID,NAME);

ALTER TABLE QUERY           ADD COLUMN     FK_FOLDER_ID int(11) default NULL;
ALTER TABLE QUERY           ADD CONSTRAINT QUERY_FK_FOLDER_ID FOREIGN KEY (FK_FOLDER_ID) REFERENCES FOLDER(ID);

ALTER TABLE FOLDER          DROP COLUMN DESCRIP;
ALTER TABLE FOLDER          DROP COLUMN GLOB;
ALTER TABLE FOLDER          DROP COLUMN COMP_AUTH;