/*
 * This file is generated by jOOQ.
*/
package stroom.data.meta.impl.db.stroom;


import javax.annotation.Generated;

import stroom.data.meta.impl.db.stroom.tables.Data;
import stroom.data.meta.impl.db.stroom.tables.DataFeed;
import stroom.data.meta.impl.db.stroom.tables.DataProcessor;
import stroom.data.meta.impl.db.stroom.tables.DataType;
import stroom.data.meta.impl.db.stroom.tables.MetaKey;
import stroom.data.meta.impl.db.stroom.tables.MetaVal;


/**
 * Convenience access to all tables in stroom
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>stroom.data</code>.
     */
    public static final Data DATA = stroom.data.meta.impl.db.stroom.tables.Data.DATA;

    /**
     * The table <code>stroom.data_feed</code>.
     */
    public static final DataFeed DATA_FEED = stroom.data.meta.impl.db.stroom.tables.DataFeed.DATA_FEED;

    /**
     * The table <code>stroom.data_processor</code>.
     */
    public static final DataProcessor DATA_PROCESSOR = stroom.data.meta.impl.db.stroom.tables.DataProcessor.DATA_PROCESSOR;

    /**
     * The table <code>stroom.data_type</code>.
     */
    public static final DataType DATA_TYPE = stroom.data.meta.impl.db.stroom.tables.DataType.DATA_TYPE;

    /**
     * The table <code>stroom.meta_key</code>.
     */
    public static final MetaKey META_KEY = stroom.data.meta.impl.db.stroom.tables.MetaKey.META_KEY;

    /**
     * The table <code>stroom.meta_val</code>.
     */
    public static final MetaVal META_VAL = stroom.data.meta.impl.db.stroom.tables.MetaVal.META_VAL;
}
