/*
 * Copyright 2016-2026 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package stroom.data.store.impl.fs.s3v2;


import stroom.util.UuidUtil;
import stroom.util.shared.ModelStringUtil;

import com.github.luben.zstd.Zstd;

import java.util.Arrays;
import java.util.Objects;
import java.util.UUID;

public class ZstdDictionary {

    private final long id;
    private final UUID uuid;
    private final byte[] dictionaryBytes;
    // Lazily cache the dict uuid bytes as we are likely to cache the dictionaries
    // for repeated use.
    private volatile byte[] uuidBytes = null;

    public ZstdDictionary(final String uuid,
                          final byte[] dictionaryBytes) {
        this(UUID.fromString(Objects.requireNonNull(uuid)), dictionaryBytes);
    }

    public ZstdDictionary(final UUID uuid,
                          final byte[] dictionaryBytes) {
        this.uuid = validateUuid(uuid);
        validateUuid(uuid);
        this.dictionaryBytes = Objects.requireNonNull(dictionaryBytes);
        if (dictionaryBytes.length == 0) {
            throw new IllegalArgumentException("Dictionary bytes must not be empty");
        }

        try {
            this.id = Zstd.getDictIdFromDict(dictionaryBytes);
        } catch (final Exception e) {
            throw new RuntimeException("Error getting dictionary id from dictionary bytes", e);
        }
    }

    private UUID validateUuid(final UUID uuid) {
        Objects.requireNonNull(uuid);
        // To allow for files to be compressed without a dictionary, we therefore can't allow
        // the creation of a ZstdDictionary with an empty UUID.
        if (uuid.getMostSignificantBits() == 0 && uuid.getLeastSignificantBits() == 0) {
            throw new IllegalArgumentException("A UUID containing all zeros is not allowed");
        }
        return uuid;
    }

    /**
     * @return The ID of this dictionary as auto-generated by the Zstd dictionary trainer, or
     * zero if not ID is set. This ID is up to four bytes in length and can be used to verify
     * that the dictionary that compressed a frame matches the dictionary being used to decompress it.
     */
    public long getId() {
        return id;
    }

    /**
     * @return The UUID of this dictionary.
     * This is a Stroom convention to uniquely identify a dictionary using 16 bytes rather than the 4 used by ID.
     * This UUID will be stored as part of the seek table footer, so the tail of a file can be parsed to
     * establish the dictionary to use for decompressing ALL frames in that file.
     */
    public UUID getUuid() {
        return uuid;
    }

    /**
     * @return The byte[] form of {@link ZstdDictionary#getUuid()}.
     */
    public byte[] getUuidBytes() {
        if (uuidBytes == null) {
            // Doesn't matter if >1 threads do this
            uuidBytes = UuidUtil.toByteArray(uuid);
        }
        return uuidBytes;
    }

    /**
     * @return The actual dictionary in byte[] form.
     */
    public byte[] getDictionaryBytes() {
        return dictionaryBytes;
    }

    /**
     * @return The size of the dictionary in bytes.
     */
    public int size() {
        return dictionaryBytes.length;
    }

    @Override
    public String toString() {
        return "ZstdDictionary{" +
               "id=" + id +
               ", name='" + uuid + '\'' +
               ", dictionarySize=" + ModelStringUtil.formatCsv(dictionaryBytes.length) +
               '}';
    }

    @Override
    public boolean equals(final Object o) {
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        final ZstdDictionary that = (ZstdDictionary) o;
        return Objects.equals(id, that.id)
               && Objects.equals(uuid, that.uuid)
               && Objects.deepEquals(dictionaryBytes, that.dictionaryBytes);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, uuid, Arrays.hashCode(dictionaryBytes));
    }
}
