/*
 * Copyright 2016-2025 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package stroom.data.store.impl.fs.s3v2;


import stroom.util.shared.ModelStringUtil;

import com.github.luben.zstd.Zstd;

import java.util.Arrays;
import java.util.Objects;

public class ZstdDictionary {

    private final long id;
    private final String uuid;
    private final byte[] dictionaryBytes;

    public ZstdDictionary(final String uuid,
                          final byte[] dictionaryBytes) {
        this.uuid = Objects.requireNonNull(uuid);
        this.dictionaryBytes = Objects.requireNonNull(dictionaryBytes);
        if (dictionaryBytes.length == 0) {
            throw new IllegalArgumentException("Dictionary bytes must not be empty");
        }

        try {
            this.id = Zstd.getDictIdFromDict(dictionaryBytes);
        } catch (final Exception e) {
            throw new RuntimeException("Error getting dictionary id from dictionary bytes", e);
        }
    }

    /**
     * @return The ID of this dictionary as ayto-generated by the Zstd dictionary trainer.
     */
    public long getId() {
        return id;
    }

    /**
     * @return The UUID of this dictionary
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * @return The actual dictionary byte[].
     */
    public byte[] getDictionaryBytes() {
        return dictionaryBytes;
    }

    /**
     * @return The size of the dictionary in bytes.
     */
    public int size() {
        return dictionaryBytes.length;
    }

    @Override
    public String toString() {
        return "ZstdDictionary{" +
               "id=" + id +
               ", name='" + uuid + '\'' +
               ", dictionarySize=" + ModelStringUtil.formatCsv(dictionaryBytes.length) +
               '}';
    }

    @Override
    public boolean equals(final Object o) {
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        final ZstdDictionary that = (ZstdDictionary) o;
        return Objects.equals(id, that.id)
               && Objects.equals(uuid, that.uuid)
               && Objects.deepEquals(dictionaryBytes, that.dictionaryBytes);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, uuid, Arrays.hashCode(dictionaryBytes));
    }
}
