/*
 * Copyright 2016-2025 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */
package stroom.annotation.impl.db.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import stroom.annotation.impl.db.jooq.Keys;
import stroom.annotation.impl.db.jooq.Stroom;
import stroom.annotation.impl.db.jooq.tables.Annotation.AnnotationPath;
import stroom.annotation.impl.db.jooq.tables.records.AnnotationEntryRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AnnotationEntry extends TableImpl<AnnotationEntryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>stroom.annotation_entry</code>
     */
    public static final AnnotationEntry ANNOTATION_ENTRY = new AnnotationEntry();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AnnotationEntryRecord> getRecordType() {
        return AnnotationEntryRecord.class;
    }

    /**
     * The column <code>stroom.annotation_entry.id</code>.
     */
    public final TableField<AnnotationEntryRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>stroom.annotation_entry.fk_annotation_id</code>.
     */
    public final TableField<AnnotationEntryRecord, Long> FK_ANNOTATION_ID = createField(DSL.name("fk_annotation_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>stroom.annotation_entry.data</code>.
     */
    public final TableField<AnnotationEntryRecord, String> DATA = createField(DSL.name("data"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>stroom.annotation_entry.entry_user_uuid</code>.
     */
    public final TableField<AnnotationEntryRecord, String> ENTRY_USER_UUID = createField(DSL.name("entry_user_uuid"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>stroom.annotation_entry.entry_time_ms</code>.
     */
    public final TableField<AnnotationEntryRecord, Long> ENTRY_TIME_MS = createField(DSL.name("entry_time_ms"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>stroom.annotation_entry.type_id</code>.
     */
    public final TableField<AnnotationEntryRecord, Byte> TYPE_ID = createField(DSL.name("type_id"), SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>stroom.annotation_entry.deleted</code>.
     */
    public final TableField<AnnotationEntryRecord, Boolean> DELETED = createField(DSL.name("deleted"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>stroom.annotation_entry.parent_id</code>.
     */
    public final TableField<AnnotationEntryRecord, Long> PARENT_ID = createField(DSL.name("parent_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stroom.annotation_entry.update_time_ms</code>.
     */
    public final TableField<AnnotationEntryRecord, Long> UPDATE_TIME_MS = createField(DSL.name("update_time_ms"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>stroom.annotation_entry.update_user_uuid</code>.
     */
    public final TableField<AnnotationEntryRecord, String> UPDATE_USER_UUID = createField(DSL.name("update_user_uuid"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private AnnotationEntry(Name alias, Table<AnnotationEntryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AnnotationEntry(Name alias, Table<AnnotationEntryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>stroom.annotation_entry</code> table reference
     */
    public AnnotationEntry(String alias) {
        this(DSL.name(alias), ANNOTATION_ENTRY);
    }

    /**
     * Create an aliased <code>stroom.annotation_entry</code> table reference
     */
    public AnnotationEntry(Name alias) {
        this(alias, ANNOTATION_ENTRY);
    }

    /**
     * Create a <code>stroom.annotation_entry</code> table reference
     */
    public AnnotationEntry() {
        this(DSL.name("annotation_entry"), null);
    }

    public <O extends Record> AnnotationEntry(Table<O> path, ForeignKey<O, AnnotationEntryRecord> childPath, InverseForeignKey<O, AnnotationEntryRecord> parentPath) {
        super(path, childPath, parentPath, ANNOTATION_ENTRY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AnnotationEntryPath extends AnnotationEntry implements Path<AnnotationEntryRecord> {
        public <O extends Record> AnnotationEntryPath(Table<O> path, ForeignKey<O, AnnotationEntryRecord> childPath, InverseForeignKey<O, AnnotationEntryRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AnnotationEntryPath(Name alias, Table<AnnotationEntryRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AnnotationEntryPath as(String alias) {
            return new AnnotationEntryPath(DSL.name(alias), this);
        }

        @Override
        public AnnotationEntryPath as(Name alias) {
            return new AnnotationEntryPath(alias, this);
        }

        @Override
        public AnnotationEntryPath as(Table<?> alias) {
            return new AnnotationEntryPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Stroom.STROOM;
    }

    @Override
    public Identity<AnnotationEntryRecord, Long> getIdentity() {
        return (Identity<AnnotationEntryRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AnnotationEntryRecord> getPrimaryKey() {
        return Keys.KEY_ANNOTATION_ENTRY_PRIMARY;
    }

    @Override
    public List<ForeignKey<AnnotationEntryRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ANNOTATION_ENTRY_FK_ANNOTATION_ID);
    }

    private transient AnnotationPath _annotation;

    /**
     * Get the implicit join path to the <code>stroom.annotation</code> table.
     */
    public AnnotationPath annotation() {
        if (_annotation == null)
            _annotation = new AnnotationPath(this, Keys.ANNOTATION_ENTRY_FK_ANNOTATION_ID, null);

        return _annotation;
    }

    @Override
    public AnnotationEntry as(String alias) {
        return new AnnotationEntry(DSL.name(alias), this);
    }

    @Override
    public AnnotationEntry as(Name alias) {
        return new AnnotationEntry(alias, this);
    }

    @Override
    public AnnotationEntry as(Table<?> alias) {
        return new AnnotationEntry(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AnnotationEntry rename(String name) {
        return new AnnotationEntry(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AnnotationEntry rename(Name name) {
        return new AnnotationEntry(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AnnotationEntry rename(Table<?> name) {
        return new AnnotationEntry(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AnnotationEntry where(Condition condition) {
        return new AnnotationEntry(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AnnotationEntry where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AnnotationEntry where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AnnotationEntry where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AnnotationEntry where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AnnotationEntry where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AnnotationEntry where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AnnotationEntry where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AnnotationEntry whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AnnotationEntry whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
