/*
 * This file is generated by jOOQ.
 */
package stroom.node.impl.db.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import stroom.node.impl.db.jooq.tables.NodeGroupLink;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class NodeGroupLinkRecord extends UpdatableRecordImpl<NodeGroupLinkRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>stroom.node_group_link.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>stroom.node_group_link.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>stroom.node_group_link.fk_node_id</code>.
     */
    public void setFkNodeId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>stroom.node_group_link.fk_node_id</code>.
     */
    public Integer getFkNodeId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>stroom.node_group_link.fk_node_group_id</code>.
     */
    public void setFkNodeGroupId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>stroom.node_group_link.fk_node_group_id</code>.
     */
    public Integer getFkNodeGroupId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NodeGroupLinkRecord
     */
    public NodeGroupLinkRecord() {
        super(NodeGroupLink.NODE_GROUP_LINK);
    }

    /**
     * Create a detached, initialised NodeGroupLinkRecord
     */
    public NodeGroupLinkRecord(Integer id, Integer fkNodeId, Integer fkNodeGroupId) {
        super(NodeGroupLink.NODE_GROUP_LINK);

        setId(id);
        setFkNodeId(fkNodeId);
        setFkNodeGroupId(fkNodeGroupId);
        resetChangedOnNotNull();
    }
}
