/*
 * This file is generated by jOOQ.
 */
package stroom.security.identity.db.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import stroom.security.identity.db.jooq.tables.Token;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TokenRecord extends UpdatableRecordImpl<TokenRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>stroom.token.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>stroom.token.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>stroom.token.version</code>.
     */
    public void setVersion(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>stroom.token.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>stroom.token.create_time_ms</code>.
     */
    public void setCreateTimeMs(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>stroom.token.create_time_ms</code>.
     */
    public Long getCreateTimeMs() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>stroom.token.create_user</code>.
     */
    public void setCreateUser(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>stroom.token.create_user</code>.
     */
    public String getCreateUser() {
        return (String) get(3);
    }

    /**
     * Setter for <code>stroom.token.update_time_ms</code>.
     */
    public void setUpdateTimeMs(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>stroom.token.update_time_ms</code>.
     */
    public Long getUpdateTimeMs() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>stroom.token.update_user</code>.
     */
    public void setUpdateUser(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>stroom.token.update_user</code>.
     */
    public String getUpdateUser() {
        return (String) get(5);
    }

    /**
     * Setter for <code>stroom.token.fk_account_id</code>.
     */
    public void setFkAccountId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>stroom.token.fk_account_id</code>.
     */
    public Integer getFkAccountId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>stroom.token.fk_token_type_id</code>.
     */
    public void setFkTokenTypeId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>stroom.token.fk_token_type_id</code>.
     */
    public Integer getFkTokenTypeId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>stroom.token.data</code>.
     */
    public void setData(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>stroom.token.data</code>.
     */
    public String getData() {
        return (String) get(8);
    }

    /**
     * Setter for <code>stroom.token.expires_on_ms</code>.
     */
    public void setExpiresOnMs(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>stroom.token.expires_on_ms</code>.
     */
    public Long getExpiresOnMs() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>stroom.token.comments</code>.
     */
    public void setComments(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>stroom.token.comments</code>.
     */
    public String getComments() {
        return (String) get(10);
    }

    /**
     * Setter for <code>stroom.token.enabled</code>.
     */
    public void setEnabled(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>stroom.token.enabled</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TokenRecord
     */
    public TokenRecord() {
        super(Token.TOKEN);
    }

    /**
     * Create a detached, initialised TokenRecord
     */
    public TokenRecord(Integer id, Integer version, Long createTimeMs, String createUser, Long updateTimeMs, String updateUser, Integer fkAccountId, Integer fkTokenTypeId, String data, Long expiresOnMs, String comments, Boolean enabled) {
        super(Token.TOKEN);

        setId(id);
        setVersion(version);
        setCreateTimeMs(createTimeMs);
        setCreateUser(createUser);
        setUpdateTimeMs(updateTimeMs);
        setUpdateUser(updateUser);
        setFkAccountId(fkAccountId);
        setFkTokenTypeId(fkTokenTypeId);
        setData(data);
        setExpiresOnMs(expiresOnMs);
        setComments(comments);
        setEnabled(enabled);
        resetTouchedOnNotNull();
    }
}
