/*
 * This file is generated by jOOQ.
 */
package stroom.docstore.impl.db.jooq;


import stroom.docstore.impl.db.jooq.tables.Doc;
import stroom.docstore.impl.db.jooq.tables.DocAudit;
import stroom.docstore.impl.db.jooq.tables.DocAuditDataSnapshot;
import stroom.docstore.impl.db.jooq.tables.DocData;
import stroom.docstore.impl.db.jooq.tables.DocDataSnapshot;


/**
 * Convenience access to all tables in stroom.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>stroom.doc</code>.
     */
    public static final Doc DOC = Doc.DOC;

    /**
     * The table <code>stroom.doc_audit</code>.
     */
    public static final DocAudit DOC_AUDIT = DocAudit.DOC_AUDIT;

    /**
     * The table <code>stroom.doc_audit_data_snapshot</code>.
     */
    public static final DocAuditDataSnapshot DOC_AUDIT_DATA_SNAPSHOT = DocAuditDataSnapshot.DOC_AUDIT_DATA_SNAPSHOT;

    /**
     * The table <code>stroom.doc_data</code>.
     */
    public static final DocData DOC_DATA = DocData.DOC_DATA;

    /**
     * The table <code>stroom.doc_data_snapshot</code>.
     */
    public static final DocDataSnapshot DOC_DATA_SNAPSHOT = DocDataSnapshot.DOC_DATA_SNAPSHOT;
}
