/*
 * This file is generated by jOOQ.
 */
package stroom.explorer.impl.db.jooq;


import stroom.explorer.impl.db.jooq.tables.ExplorerPath;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in stroom.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index EXPLORER_PATH_EXPLORER_PATH_ANCESTOR_DEPTH_ORDER_INDEX = Internal.createIndex(DSL.name("explorer_path_ancestor_depth_order_index"), ExplorerPath.EXPLORER_PATH, new OrderField[] { ExplorerPath.EXPLORER_PATH.ANCESTOR, ExplorerPath.EXPLORER_PATH.DEPTH, ExplorerPath.EXPLORER_PATH.ORDER_INDEX }, false);
    public static final Index EXPLORER_PATH_EXPLORER_PATH_DEPTH = Internal.createIndex(DSL.name("explorer_path_depth"), ExplorerPath.EXPLORER_PATH, new OrderField[] { ExplorerPath.EXPLORER_PATH.DEPTH }, false);
    public static final Index EXPLORER_PATH_EXPLORER_PATH_DESCENDANT = Internal.createIndex(DSL.name("explorer_path_descendant"), ExplorerPath.EXPLORER_PATH, new OrderField[] { ExplorerPath.EXPLORER_PATH.DESCENDANT }, false);
    public static final Index EXPLORER_PATH_EXPLORER_PATH_DESCENDANT_DEPTH = Internal.createIndex(DSL.name("explorer_path_descendant_depth"), ExplorerPath.EXPLORER_PATH, new OrderField[] { ExplorerPath.EXPLORER_PATH.DESCENDANT, ExplorerPath.EXPLORER_PATH.DEPTH }, false);
}
