/*
 * This file is generated by jOOQ.
 */
package stroom.explorer.impl.db.jooq;


import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import stroom.explorer.impl.db.jooq.tables.ExplorerFavourite;
import stroom.explorer.impl.db.jooq.tables.ExplorerNode;
import stroom.explorer.impl.db.jooq.tables.ExplorerPath;
import stroom.explorer.impl.db.jooq.tables.TabSession;
import stroom.explorer.impl.db.jooq.tables.TabSessionDocRef;
import stroom.explorer.impl.db.jooq.tables.records.ExplorerFavouriteRecord;
import stroom.explorer.impl.db.jooq.tables.records.ExplorerNodeRecord;
import stroom.explorer.impl.db.jooq.tables.records.ExplorerPathRecord;
import stroom.explorer.impl.db.jooq.tables.records.TabSessionDocRefRecord;
import stroom.explorer.impl.db.jooq.tables.records.TabSessionRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * stroom.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ExplorerFavouriteRecord> KEY_EXPLORER_FAVOURITE_EXPLORER_FAVOURITE_USER_UUID_EXPLORER_NODE_ID_IDX = Internal.createUniqueKey(ExplorerFavourite.EXPLORER_FAVOURITE, DSL.name("KEY_explorer_favourite_explorer_favourite_user_uuid_explorer_node_id_idx"), new TableField[] { ExplorerFavourite.EXPLORER_FAVOURITE.EXPLORER_NODE_ID, ExplorerFavourite.EXPLORER_FAVOURITE.USER_UUID }, true);
    public static final UniqueKey<ExplorerFavouriteRecord> KEY_EXPLORER_FAVOURITE_PRIMARY = Internal.createUniqueKey(ExplorerFavourite.EXPLORER_FAVOURITE, DSL.name("KEY_explorer_favourite_PRIMARY"), new TableField[] { ExplorerFavourite.EXPLORER_FAVOURITE.ID }, true);
    public static final UniqueKey<ExplorerNodeRecord> KEY_EXPLORER_NODE_EXPLORER_NODE_TYPE_UUID = Internal.createUniqueKey(ExplorerNode.EXPLORER_NODE, DSL.name("KEY_explorer_node_explorer_node_type_uuid"), new TableField[] { ExplorerNode.EXPLORER_NODE.TYPE, ExplorerNode.EXPLORER_NODE.UUID }, true);
    public static final UniqueKey<ExplorerNodeRecord> KEY_EXPLORER_NODE_PRIMARY = Internal.createUniqueKey(ExplorerNode.EXPLORER_NODE, DSL.name("KEY_explorer_node_PRIMARY"), new TableField[] { ExplorerNode.EXPLORER_NODE.ID }, true);
    public static final UniqueKey<ExplorerPathRecord> KEY_EXPLORER_PATH_PRIMARY = Internal.createUniqueKey(ExplorerPath.EXPLORER_PATH, DSL.name("KEY_explorer_path_PRIMARY"), new TableField[] { ExplorerPath.EXPLORER_PATH.ANCESTOR, ExplorerPath.EXPLORER_PATH.DESCENDANT }, true);
    public static final UniqueKey<TabSessionRecord> KEY_TAB_SESSION_PRIMARY = Internal.createUniqueKey(TabSession.TAB_SESSION, DSL.name("KEY_tab_session_PRIMARY"), new TableField[] { TabSession.TAB_SESSION.ID }, true);
    public static final UniqueKey<TabSessionRecord> KEY_TAB_SESSION_TAB_SESSION_NAME_USER_UUID_IDX = Internal.createUniqueKey(TabSession.TAB_SESSION, DSL.name("KEY_tab_session_tab_session_name_user_uuid_idx"), new TableField[] { TabSession.TAB_SESSION.NAME, TabSession.TAB_SESSION.USER_UUID }, true);
    public static final UniqueKey<TabSessionDocRefRecord> KEY_TAB_SESSION_DOC_REF_PRIMARY = Internal.createUniqueKey(TabSessionDocRef.TAB_SESSION_DOC_REF, DSL.name("KEY_tab_session_doc_ref_PRIMARY"), new TableField[] { TabSessionDocRef.TAB_SESSION_DOC_REF.TAB_SESSION_ID, TabSessionDocRef.TAB_SESSION_DOC_REF.DOC_REF_TYPE, TabSessionDocRef.TAB_SESSION_DOC_REF.DOC_REF_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ExplorerFavouriteRecord, ExplorerNodeRecord> EXPLORER_FAVOURITE_EXPLORER_NODE_ID = Internal.createForeignKey(ExplorerFavourite.EXPLORER_FAVOURITE, DSL.name("explorer_favourite_explorer_node_id"), new TableField[] { ExplorerFavourite.EXPLORER_FAVOURITE.EXPLORER_NODE_ID }, Keys.KEY_EXPLORER_NODE_PRIMARY, new TableField[] { ExplorerNode.EXPLORER_NODE.ID }, true);
    public static final ForeignKey<TabSessionDocRefRecord, TabSessionRecord> TAB_SESSION_DOC_REF_TAB_SESSION_ID = Internal.createForeignKey(TabSessionDocRef.TAB_SESSION_DOC_REF, DSL.name("tab_session_doc_ref_tab_session_id"), new TableField[] { TabSessionDocRef.TAB_SESSION_DOC_REF.TAB_SESSION_ID }, Keys.KEY_TAB_SESSION_PRIMARY, new TableField[] { TabSession.TAB_SESSION.ID }, true);
}
