/*
 * This file is generated by jOOQ.
 */
package stroom.explorer.impl.db.jooq;


import javax.annotation.processing.Generated;

import stroom.explorer.impl.db.jooq.tables.ExplorerNode;
import stroom.explorer.impl.db.jooq.tables.ExplorerPath;


/**
 * Convenience access to all tables in stroom
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>stroom.explorer_node</code>.
     */
    public static final ExplorerNode EXPLORER_NODE = ExplorerNode.EXPLORER_NODE;

    /**
     * The table <code>stroom.explorer_path</code>.
     */
    public static final ExplorerPath EXPLORER_PATH = ExplorerPath.EXPLORER_PATH;
}
