/*
 * This file is generated by jOOQ.
 */
package stroom.meta.impl.db.jooq.tables.records;


import stroom.meta.impl.db.jooq.tables.MetaVal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MetaValRecord extends UpdatableRecordImpl<MetaValRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>stroom.meta_val.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>stroom.meta_val.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>stroom.meta_val.create_time</code>.
     */
    public void setCreateTime(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>stroom.meta_val.create_time</code>.
     */
    public Long getCreateTime() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>stroom.meta_val.meta_id</code>.
     */
    public void setMetaId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>stroom.meta_val.meta_id</code>.
     */
    public Long getMetaId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>stroom.meta_val.meta_key_id</code>.
     */
    public void setMetaKeyId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>stroom.meta_val.meta_key_id</code>.
     */
    public Integer getMetaKeyId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>stroom.meta_val.val</code>.
     */
    public void setVal(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>stroom.meta_val.val</code>.
     */
    public Long getVal() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MetaValRecord
     */
    public MetaValRecord() {
        super(MetaVal.META_VAL);
    }

    /**
     * Create a detached, initialised MetaValRecord
     */
    public MetaValRecord(Long id, Long createTime, Long metaId, Integer metaKeyId, Long val) {
        super(MetaVal.META_VAL);

        setId(id);
        setCreateTime(createTime);
        setMetaId(metaId);
        setMetaKeyId(metaKeyId);
        setVal(val);
        resetChangedOnNotNull();
    }
}
