/*
 * This file is generated by jOOQ.
 */
package stroom.credentials.impl.db.jooq;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import stroom.credentials.impl.db.jooq.tables.Credentials;
import stroom.credentials.impl.db.jooq.tables.records.CredentialsRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * stroom.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CredentialsRecord> KEY_CREDENTIALS_PRIMARY = Internal.createUniqueKey(Credentials.CREDENTIALS, DSL.name("KEY_credentials_PRIMARY"), new TableField[] { Credentials.CREDENTIALS.UUID }, true);
}
