/*
 * This file is generated by jOOQ.
 */
package stroom.sqlstore.impl.db.jooq;


import stroom.sqlstore.impl.db.jooq.tables.UpdatableTemporalStore;


/**
 * Convenience access to all tables in stroom.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>stroom.updatable_temporal_store</code>.
     */
    public static final UpdatableTemporalStore UPDATABLE_TEMPORAL_STORE = UpdatableTemporalStore.UPDATABLE_TEMPORAL_STORE;
}
