/*
 * Copyright 2026 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// What the self-test checks. See README.md.

/// HTML snippets whose elements' roles (as `*ByRole` queries see them), accessible names and
/// accessibility (as Testing Library's isInaccessible decides) are compared with Testing Library's.
export const ARIA_SNIPPETS = [
  "<input>",
  "<input type=\"email\" list=\"\">",
  "<input list=\"\">",
  "<input type=\"search\" list=\"\">",
  "<input type=\"text\" list=\"dl\">",
  "<input type=\"FOO\">",
  "<input type=\"password\">",
  "<input type=\"number\" list=\"dl\">",
  "<input type=\"hidden\">",
  "<select size=\"1\"><option>a</option></select>",
  "<select size=\"3\"><option>a</option></select>",
  "<select multiple><option>a</option></select>",
  "<a>x</a>",
  "<a href=\"\">x</a>",
  "<a href=\"#\">x</a>",
  "<img alt=\"\">",
  "<img>",
  "<img alt=\"x\">",
  "<img alt=\"\" aria-label=\"z\">",
  "<table><tr><th scope=\"Row\">h</th><th>c</th><td>d</td></tr></table>",
  "<section>s</section>",
  "<section aria-label=\"\">s</section>",
  "<section aria-label=\"S\">s</section>",
  "<aside>a</aside>",
  "<header>h</header>",
  "<footer>f</footer>",
  "<form>f</form>",
  "<form name=\"n\">f</form>",
  "<form aria-label=\"F\">f</form>",
  "<ul><li>a</li></ul>",
  "<div><li>x</li></div>",
  "<summary>s</summary>",
  "<details><summary>s</summary>d</details>",
  "<div role=\"\">x</div>",
  "<div role=\" button\">x</div>",
  "<div role=\"button link\">x</div>",
  "<div role=\"presentation\" aria-description=\"d\">x</div>",
  "<div role=\"none\" aria-label=\"q\">x</div>",
  "<button role=\"presentation\" aria-label=\"q\">x</button>",
  "<button>Save <span hidden>x</span><span style=\"display:none\">y</span><span aria-hidden=\"true\">z</span></button>",
  "<button aria-labelledby=\"lb1 lb2\">x</button><span id=\"lb1\">One</span><span id=\"lb2\" hidden>Two</span>",
  "<label>Name <input value=\"v\"></label>",
  "<label for=\"i9\">L9</label><input id=\"i9\" aria-label=\"AL\">",
  "<button><img alt=\"pic\"> text</button>",
  "<button title=\"T\"></button>",
  "<div title=\"T\">x</div>",
  "<fieldset><legend>Leg</legend><input></fieldset>",
  "<table><caption>Cap</caption><tr><td>1</td></tr></table>",
  "<label>Choose <select><option selected>Opt</option></select></label>",
  "<label>Range <input type=\"range\" value=\"7\"></label>",
  "<label>Box <div role=\"textbox\">tb</div></label>",
  "<button><div>A</div><div>B</div></button>",
  "<button>A<span>B</span></button>",
  "<div role=\"tab\"><span>T</span><svg><title>ST</title></svg></div>",
  "<svg><title>Svg title</title></svg>",
  "<input type=\"submit\">",
  "<input type=\"reset\" value=\"\">",
  "<input type=\"image\">",
  "<input type=\"button\" value=\"IB\">",
  "<h2>Heading <em>x</em></h2>",
  "<div role=\"menu\" aria-label=\"\">m</div>",
  "<li role=\"menuitem\">Item <span style=\"visibility:hidden\">hid</span></li>",
  "<div role=\"option\" aria-selected=\"true\">opt</div>",
  "<button style=\"visibility:hidden\">vh</button>",
  "<div aria-hidden=\"true\"><button>ah</button></div>",
  "<output>o</output>",
  "<meter value=\"1\">m</meter>",
  "<progress>p</progress>",
  "<dialog open>dlg</dialog>",
  "<address>ad</address>",
  "<td>orphan</td>",
  "<math></math>",
  "<hgroup></hgroup>",
  "<search>s</search>",
  "<menu><li>m</li></menu>",
  "<datalist id=\"dl\"></datalist>",
  "<optgroup label=\"og\"></optgroup>",
  "<dt>t</dt>",
  "<dfn>d</dfn>",
  "<b>b</b>",
  "<code>c</code>",
  "<p aria-label=\"pp\">p</p>",
  "<input type=\"text\" list=\"dl\"><datalist id=\"dl\"><option>a</option></datalist>",
  "<input type=\"email\" list=\"dl2\"><datalist id=\"dl2\"></datalist>",
  "<table><tr><th scope=\"ROW\">h</th><th scope=\"rowgroup\">g</th><th scope=\"Col\">c</th></tr></table>",
  "<div role=\"none\" aria-description=\"d\">x</div>",
  "<div role=\"presentation\" aria-describedby=\"x\">x</div>",
  "<details><summary>Sum</summary><p>Body</p></details>",
  "<div hidden><button>hb</button></div>",
  "<div style=\"visibility:collapse\"><button>vc</button></div>",
  "<input type=\"checkbox\" aria-label=\"cb\"><input type=\"radio\" aria-label=\"rb\">",
  "<select><option>One</option><option selected>Two</option></select>",
  "<button role=\"presentation\" aria-description=\"d\">Text</button>",
  "<button role=\"presentation\" aria-describedby=\"x\">Text</button><span id=\"x\">desc</span>",
  "<label>Field <input type=\"checkbox\" value=\"on\"></label><input type=\"file\" aria-label=\"Upload\">",
];

/// HTML snippets whose elements' visibility, checked state and disabled state are compared with
/// jest-dom's toBeVisible, toBeChecked and toBeDisabled.
export const MATCHER_SNIPPETS = [
  '<div id="a">shown</div>',
  '<div id="a" hidden>hidden</div>',
  '<div hidden><span id="a">in hidden</span></div>',
  '<div style="visibility:collapse"><span id="a">collapsed</span></div>',
  '<div style="opacity:0"><span id="a">transparent</span></div>',
  '<div style="display:none"><span id="a">not displayed</span></div>',
  '<details id="a"><summary id="b">Summary</summary><p id="c">Body</p></details>',
  '<details id="a" open><summary id="b">Summary</summary><p id="c">Body</p></details>',
  '<input id="a" type="checkbox" checked><input id="b" type="radio"><div id="c">x</div>',
  '<div id="a" role="checkbox" aria-checked="true">x</div><div id="b" role="switch" aria-checked="mixed">y</div>',
  '<div id="a" role="button" aria-checked="true">x</div><span id="b" aria-checked="true">z</span>',
  '<fieldset disabled><legend><input id="a"></legend><input id="b"></fieldset><button id="c" disabled>c</button>',
  '<div id="a" aria-disabled="true">a</div><my-widget id="b" disabled>b</my-widget>',
];

/// Styles compared with jest-dom's toHaveStyle: [snippet, property, expected value].
export const STYLE_CASES = [
  ['<div id="a" style="color: red">x</div>', 'color', 'red'],
  ['<div id="a" style="color: red">x</div>', 'color', 'rgb(255, 0, 0)'],
  ['<div id="a" style="color: red">x</div>', 'color', '#f00'],
  ['<div id="a" style="font-weight: bold">x</div>', 'font-weight', 'bold'],
  ['<div id="a" style="font-weight: bold">x</div>', 'font-weight', '700'],
  ['<div id="a" style="display: none">x</div>', 'display', 'none'],
  ['<div id="a" style="display: none">x</div>', 'display', 'nonsense'],
  ['<div id="a" style="width: 10px">x</div>', 'width', '10px'],
  ['<div id="a" style="--gap: 4px">x</div>', '--gap', '4px'],
  ['<div id="a" style="background-color: transparent">x</div>', 'background-color', 'transparent'],
];

const RADIOS = '<input type="radio" name="g" id="r1"><input type="radio" name="g" id="r2" checked>'
  + '<input type="radio" name="g" id="r3"><button id="after">after</button>';

/// Interactions run with user-event and with the workbench's port, comparing the events fired and
/// the resulting state. Each action is [name, selector, text]; `setup` (optional) is JavaScript
/// run in the page, with `host` the element holding the snippet, before the actions.
export const SCENARIOS = [
  { name: 'click puts the caret at the end of a text field', html: '<input id="t" value="hello world">',
    actions: [['click', '#t']] },
  { name: 'double click selects the last word', html: '<input id="t" value="hello world">',
    actions: [['dblClick', '#t']] },
  { name: 'double click selects trailing punctuation', html: '<input id="t" value="hello world!">',
    actions: [['dblClick', '#t']] },
  { name: 'triple click selects the last line', html: '<textarea id="t">line one\nline two</textarea>',
    actions: [['tripleClick', '#t']] },
  { name: 'click on text puts the document caret at its end',
    html: '<div id="d">some <b id="b">bold</b> text</div>', actions: [['click', '#d']] },
  { name: 'double click on text selects its last word',
    html: '<div id="d">some <b id="b">bold</b> words</div>', actions: [['dblClick', '#d']] },
  { name: 'click events', html: '<div id="outer"><button id="btn">Go</button></div>',
    actions: [['click', '#btn']] },
  { name: 'second click starts from the body again', html: '<div id="outer"><button id="btn">Go</button></div>',
    actions: [['click', '#btn'], ['click', '#btn']] },
  { name: 'double click events', html: '<button id="btn">Go</button>', actions: [['dblClick', '#btn']] },
  { name: 'right click', html: '<div id="outer"><span id="s">menu</span></div>', actions: [['rightClick', '#s']] },
  { name: 'click on a disabled button', html: '<div id="outer"><button id="btn" disabled>No</button></div>',
    actions: [['click', '#btn']] },
  { name: 'click in a disabled field set', html: '<fieldset disabled><input id="i"></fieldset>',
    actions: [['click', '#i']] },
  { name: 'cancelled mousedown moves neither caret nor focus', html: '<input id="t" value="abc">',
    setup: "host.querySelector('#t').addEventListener('mousedown', e => e.preventDefault());",
    actions: [['click', '#t']] },
  { name: 'cancelled pointerdown', html: '<button id="btn">Go</button>',
    setup: "host.querySelector('#btn').addEventListener('pointerdown', e => e.preventDefault());",
    actions: [['click', '#btn']] },
  { name: 'pointer-events none fails', html: '<div style="pointer-events:none"><button id="btn">x</button></div>',
    actions: [['click', '#btn']] },
  { name: 'hover enters each ancestor', html: '<div id="outer"><div id="mid"><button id="btn">x</button></div></div>',
    actions: [['hover', '#btn']] },
  { name: 'unhover only moves over the body', html: '<div id="outer"><button id="btn">x</button></div>',
    actions: [['hover', '#btn'], ['unhover', '#btn']] },
  { name: 'click on a label clicks its control', html: '<label id="l" for="c">Label</label><input type="checkbox" id="c">',
    actions: [['click', '#l']] },
  { name: 'click on a file input', html: '<input type="file" id="f">', actions: [['click', '#f']] },
  { name: 'tab order', html: '<button id="a">a</button><input id="b"><a id="c" href="#x">c</a>'
      + '<div id="d" tabindex="2">d</div><span id="e" tabindex="1">e</span><button id="f" disabled>f</button>'
      + '<input id="g" type="hidden"><fieldset disabled><input id="h"></fieldset><div id="i" tabindex="-1">i</div>'
      + '<button id="j" style="display:none">j</button><button id="k">k</button>',
    actions: [['tab'], ['tab'], ['tab'], ['tab'], ['tab'], ['tab'], ['tab'], ['tab']] },
  { name: 'shift tab from the first element goes to the body',
    html: '<span id="e" tabindex="1">e</span><button id="a">a</button>',
    actions: [['tab'], ['shiftTab'], ['shiftTab']] },
  { name: 'tab into a radio group', html: RADIOS, actions: [['tab'], ['tab'], ['tab'], ['tab']] },
  { name: 'tab selects the text of a field', html: '<input id="a" value="abc"><textarea id="b">defg</textarea>',
    actions: [['tab'], ['tab']] },
  { name: 'arrow keys walk a radio group', html: RADIOS,
    actions: [['click', '#r1'], ['keyboard', null, '{ArrowDown}'], ['keyboard', null, '{ArrowRight}'],
      ['keyboard', null, '{ArrowLeft}'], ['keyboard', null, '{ArrowUp}']] },
  { name: 'typing into a number field', html: '<input id="n" type="number">', actions: [['type', '#n', '1.5e-3']] },
  { name: 'typing letters into a number field', html: '<input id="n" type="number">', actions: [['type', '#n', '1a2']] },
  { name: 'maxlength limits text but not tel fields',
    html: '<input id="t" maxlength="3"><input id="p" type="tel" maxlength="3">',
    actions: [['type', '#t', '12345'], ['type', '#p', '12345']] },
  { name: 'typing a time', html: '<input id="t" type="time">', actions: [['type', '#t', '0930']] },
  { name: 'typing into a date field', html: '<input id="d" type="date">', actions: [['type', '#d', '2024-01-31']] },
  { name: 'typing into a content editable element keeps its markup',
    html: '<div id="ce" contenteditable="true">Hello <b>bold</b></div>', actions: [['type', '#ce', ' X']] },
  { name: 'deleting in a content editable element',
    html: '<div id="ce" contenteditable="true">Hi <b>there</b></div>', actions: [['type', '#ce', '{Backspace}{Backspace}']] },
  { name: 'Enter in a content editable element', html: '<div id="ce" contenteditable="">Line</div>',
    actions: [['type', '#ce', '{Enter}x']] },
  { name: 'editing keys in a text field', html: '<input id="t" value="abcdef">',
    actions: [['type', '#t', '{ArrowLeft}{ArrowLeft}X{Home}Y{End}Z{Backspace}{ArrowLeft}{Delete}']] },
  { name: 'select all then type', html: '<input id="t" value="abc">',
    actions: [['type', '#t', '{Control>}a{/Control}Z']] },
  { name: 'Meta+A types rather than selecting', html: '<input id="t" value="abc">',
    actions: [['type', '#t', '{Meta>}a{/Meta}']] },
  { name: 'Enter in a text area', html: '<textarea id="t">a</textarea>', actions: [['type', '#t', '{Enter}b']] },
  { name: 'Enter submits with the default button',
    html: '<form id="f"><input id="i"><button id="s">Go</button></form>',
    setup: "host.querySelector('#f').addEventListener('submit', e => e.preventDefault());",
    actions: [['type', '#i', 'x{Enter}']] },
  { name: 'Enter submits a form with a single input', html: '<form id="f"><input id="i"></form>',
    setup: "host.querySelector('#f').addEventListener('submit', e => e.preventDefault());",
    actions: [['type', '#i', '{Enter}']] },
  { name: 'Enter does nothing in a form with two inputs and no button',
    html: '<form id="f"><input id="i"><input id="j"></form>',
    setup: "host.querySelector('#f').addEventListener('submit', e => e.preventDefault());",
    actions: [['type', '#i', '{Enter}']] },
  { name: 'Enter with Control or Meta on a button', html: '<button id="b">b</button>',
    actions: [['click', '#b'], ['keyboard', null, '{Control>}{Enter}{/Control}'],
      ['keyboard', null, '{Meta>}{Enter}{/Meta}'], ['keyboard', null, '{Alt>}{Enter}{/Alt}']] },
  { name: 'Enter and Space on a colour input', html: '<input type="color" id="c">',
    actions: [['click', '#c'], ['keyboard', null, '{Enter}'], ['keyboard', null, ' ']] },
  { name: 'Space on a check box', html: '<input type="checkbox" id="c">',
    actions: [['click', '#c'], ['keyboard', null, ' ']] },
  { name: 'Space does nothing if its keyup is cancelled', html: '<input type="checkbox" id="c">',
    setup: "host.querySelector('#c').addEventListener('keyup', e => e.preventDefault());",
    actions: [['click', '#c'], ['keyboard', null, ' ']] },
  { name: 'Space does nothing if its keydown is cancelled', html: '<button id="b">b</button>',
    setup: "host.querySelector('#b').addEventListener('keydown', e => e.preventDefault());",
    actions: [['click', '#b'], ['keyboard', null, ' ']] },
  { name: 'releasing a key that is not held', html: '<input id="t">',
    actions: [['click', '#t'], ['keyboard', null, '{/Shift}a{Shift>}b']] },
  { name: 'type releases the keys still held', html: '<input id="t">', actions: [['type', '#t', '{Shift>}A']] },
  { name: 'clear a text field', html: '<input id="t" value="abc">', actions: [['clear', '#t']] },
  { name: 'clear a content editable element', html: '<div id="ce" contenteditable="true">a<b>b</b></div>',
    actions: [['clear', '#ce']] },
  { name: 'typing into a read only field', html: '<input id="t" value="a" readonly>', actions: [['type', '#t', 'b']] },
  { name: 'typing into a disabled field', html: '<input id="t" value="a" disabled>', actions: [['type', '#t', 'b']] },
  { name: 'typing then tabbing away fires change', html: '<input id="a"><input id="b">',
    actions: [['type', '#a', 'xy'], ['tab']] },
  { name: 'the program changing the value while typing',
    html: '<input id="t">',
    setup: "const t = host.querySelector('#t'); t.addEventListener('input', () => { t.value = t.value.toUpperCase(); });",
    actions: [['type', '#t', 'ab{ArrowLeft}c']] },
  { name: 'the program selecting while typing', html: '<input id="t" value="hello">',
    setup: "const t = host.querySelector('#t'); t.addEventListener('focus', () => t.setSelectionRange(1, 2));",
    actions: [['click', '#t'], ['keyboard', null, 'X']] },
  { name: 'click on a check box in a label', html: '<label id="l">Tick <input type="checkbox" id="c"></label>',
    actions: [['click', '#l'], ['click', '#c']] },
  { name: 'click on a select', html: '<select id="s"><option>a</option><option>b</option></select>',
    actions: [['click', '#s']] },
  { name: 'keys with nothing focused', html: '<div id="d">text</div>',
    actions: [['keyboard', null, 'a{Enter} {Tab}']] },
  { name: 'Space and Enter on a button', html: '<button id="b">b</button>',
    actions: [['click', '#b'], ['keyboard', null, ' '], ['keyboard', null, '{Enter}']] },
  { name: 'Control+A outside a field selects the page', html: '<div id="d">text</div>',
    actions: [['click', '#d'], ['keyboard', null, '{Control>}a{/Control}']] },
  { name: 'arrow keys in a content editable element',
    html: '<div id="ce" contenteditable="true">abc</div>',
    actions: [['click', '#ce'], ['keyboard', null, '{ArrowLeft}{ArrowLeft}X{ArrowRight}Y']] },
  { name: 'Home and End in a text area', html: '<textarea id="t">one\ntwo</textarea>',
    actions: [['type', '#t', '{Home}A{End}B{PageUp}C{PageDown}D']] },
  { name: 'tab from an element with a negative tab index',
    html: '<button id="a" tabindex="2">a</button><div id="n" tabindex="-1">n</div><button id="b">b</button>',
    actions: [['click', '#n'], ['tab']] },
  { name: 'shift tab from the body', html: '<button id="a">a</button><button id="b">b</button>',
    actions: [['shiftTab'], ['shiftTab']] },
  { name: 'hover then click', html: '<div id="outer"><button id="btn">Go</button></div>',
    actions: [['hover', '#btn'], ['click', '#btn']] },
  { name: 'double click in a content editable element',
    html: '<div id="ce" contenteditable="true">one two</div>', actions: [['dblClick', '#ce']] },
  { name: 'cancelled keydown stops typing', html: '<input id="t">',
    setup: "host.querySelector('#t').addEventListener('keydown', e => { if (e.key === 'b') e.preventDefault(); });",
    actions: [['type', '#t', 'abc']] },
  { name: 'cancelled keypress stops typing', html: '<input id="t">',
    setup: "host.querySelector('#t').addEventListener('keypress', e => { if (e.key === 'b') e.preventDefault(); });",
    actions: [['type', '#t', 'abc']] },
  { name: 'cancelled beforeinput stops typing', html: '<input id="t">',
    setup: "host.querySelector('#t').addEventListener('beforeinput', e => { if (e.data === 'b') e.preventDefault(); });",
    actions: [['type', '#t', 'abc']] },
  { name: 'unhover an element without pointer events',
    html: '<div style="pointer-events:none"><button id="btn">x</button></div>', actions: [['unhover', '#btn']] },
  { name: 'fireEvent defaults', html: '<div id="d">d</div>',
    actions: [['fireEvent', '#d', 'contextMenu'], ['fireEvent', '#d', 'mouseDown'], ['fireEvent', '#d', 'pointerDown'],
      ['fireEvent', '#d', 'click'], ['fireEvent', '#d', 'mouseEnter']] },
];
