/*
 * This file is generated by jOOQ.
 */
package stroom.index.impl.db;


import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import stroom.index.impl.db.tables.IndexShard;
import stroom.index.impl.db.tables.IndexVolume;
import stroom.index.impl.db.tables.Node;
import stroom.index.impl.db.tables.Rack;


/**
 * A class modelling indexes of tables of the <code>stroom</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index INDEX_PRIMARY = Indexes0.INDEX_PRIMARY;
    public static final Index INDEX_UUID = Indexes0.INDEX_UUID;
    public static final Index INDEX_SHARD_INDEX_SHARD_FK_INDEX_ID = Indexes0.INDEX_SHARD_INDEX_SHARD_FK_INDEX_ID;
    public static final Index INDEX_SHARD_INDEX_SHARD_FK_NODE_ID = Indexes0.INDEX_SHARD_INDEX_SHARD_FK_NODE_ID;
    public static final Index INDEX_SHARD_INDEX_SHARD_FK_VOLUME_ID = Indexes0.INDEX_SHARD_INDEX_SHARD_FK_VOLUME_ID;
    public static final Index INDEX_SHARD_PRIMARY = Indexes0.INDEX_SHARD_PRIMARY;
    public static final Index INDEX_VOLUME_NODE_NAME_PATH = Indexes0.INDEX_VOLUME_NODE_NAME_PATH;
    public static final Index INDEX_VOLUME_PRIMARY = Indexes0.INDEX_VOLUME_PRIMARY;
    public static final Index NODE_NAME = Indexes0.NODE_NAME;
    public static final Index NODE_NODE_FK_RACK_ID = Indexes0.NODE_NODE_FK_RACK_ID;
    public static final Index NODE_PRIMARY = Indexes0.NODE_PRIMARY;
    public static final Index RACK_NAME = Indexes0.RACK_NAME;
    public static final Index RACK_PRIMARY = Indexes0.RACK_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index INDEX_PRIMARY = Internal.createIndex("PRIMARY", stroom.index.impl.db.tables.Index.INDEX, new OrderField[] { stroom.index.impl.db.tables.Index.INDEX.ID }, true);
        public static Index INDEX_UUID = Internal.createIndex("uuid", stroom.index.impl.db.tables.Index.INDEX, new OrderField[] { stroom.index.impl.db.tables.Index.INDEX.UUID }, true);
        public static Index INDEX_SHARD_INDEX_SHARD_FK_INDEX_ID = Internal.createIndex("index_shard_fk_index_id", IndexShard.INDEX_SHARD, new OrderField[] { IndexShard.INDEX_SHARD.OLD_INDEX_ID }, false);
        public static Index INDEX_SHARD_INDEX_SHARD_FK_NODE_ID = Internal.createIndex("index_shard_fk_node_id", IndexShard.INDEX_SHARD, new OrderField[] { IndexShard.INDEX_SHARD.FK_NODE_ID }, false);
        public static Index INDEX_SHARD_INDEX_SHARD_FK_VOLUME_ID = Internal.createIndex("index_shard_fk_volume_id", IndexShard.INDEX_SHARD, new OrderField[] { IndexShard.INDEX_SHARD.FK_VOLUME_ID }, false);
        public static Index INDEX_SHARD_PRIMARY = Internal.createIndex("PRIMARY", IndexShard.INDEX_SHARD, new OrderField[] { IndexShard.INDEX_SHARD.ID }, true);
        public static Index INDEX_VOLUME_NODE_NAME_PATH = Internal.createIndex("node_name_path", IndexVolume.INDEX_VOLUME, new OrderField[] { IndexVolume.INDEX_VOLUME.NODE_NAME, IndexVolume.INDEX_VOLUME.PATH }, true);
        public static Index INDEX_VOLUME_PRIMARY = Internal.createIndex("PRIMARY", IndexVolume.INDEX_VOLUME, new OrderField[] { IndexVolume.INDEX_VOLUME.ID }, true);
        public static Index NODE_NAME = Internal.createIndex("NAME", Node.NODE, new OrderField[] { Node.NODE.NAME }, true);
        public static Index NODE_NODE_FK_RACK_ID = Internal.createIndex("node_fk_rack_id", Node.NODE, new OrderField[] { Node.NODE.FK_RACK_ID }, false);
        public static Index NODE_PRIMARY = Internal.createIndex("PRIMARY", Node.NODE, new OrderField[] { Node.NODE.ID }, true);
        public static Index RACK_NAME = Internal.createIndex("NAME", Rack.RACK, new OrderField[] { Rack.RACK.NAME }, true);
        public static Index RACK_PRIMARY = Internal.createIndex("PRIMARY", Rack.RACK, new OrderField[] { Rack.RACK.ID }, true);
    }
}
